rpm-software-management/mock

etc/mock/mageia-6-armv5tl.cfg
etc/mock/mageia-6-armv7hl.cfg
etc/mock/mageia-6-i586.cfg
etc/mock/mageia-6-x86_64.cfg
etc/mock/mageia-cauldron-armv5tl.cfg
etc/mock/mageia-cauldron-armv7hl.cfg
etc/mock/mageia-cauldron-i586.cfg
etc/mock/mageia-cauldron-x86_64.cfg

This is consistent with the file name in mageia-repos-keys package and the one previously used.
This PR depends on xsuchy/distribution-gpg-keys#1

Rename mageia pubkey to RPM-GPG-KEY-Mageia

---

etc/bash_completion.d/mock

The -r option accepts pathnames of files with .cfg extensions,
so make the bash completion also expand suitable files and
directories.

Add bash completion for .cfg files outside /etc/mock

---

etc/mock/epel-5-i386.cfg
etc/mock/epel-5-ppc.cfg
etc/mock/epel-5-x86_64.cfg
etc/mock/epel-6-i386.cfg
etc/mock/epel-6-ppc64.cfg
etc/mock/epel-6-x86_64.cfg
etc/mock/epel-7-aarch64.cfg
etc/mock/epel-7-ppc64le.cfg
etc/mock/epel-7-x86_64.cfg
etc/mock/fedora-rawhide-aarch64.cfg
etc/mock/fedora-rawhide-armhfp.cfg
etc/mock/fedora-rawhide-i386.cfg
etc/mock/fedora-rawhide-ppc64.cfg
etc/mock/fedora-rawhide-ppc64le.cfg
etc/mock/fedora-rawhide-s390.cfg
etc/mock/fedora-rawhide-s390x.cfg
etc/mock/fedora-rawhide-x86_64.cfg

dnf debuginfo-install needs the debug repo to be named
${repo}-debuginfo, where ${repo} is the name of the main repo.
Otherwise, it doesn't find it.

Fix debuginfo repo naming

---

etc/mock/site-defaults.cfg
py/mockbuild/util.py

Since it is list, not string [everywhere](https://github.com/rpm-software-management/mock/blob/55ea53f5a1ebc84017f947a48326658b8df6ce3a/py/mockbuild/package_manager.py#L270).
I just added `config_opts['yum_builddep_opts'] = '--verbose'` and...
```
$ mock --resultdir acl -r epel-7-x86_64 acl-2.2.51-12.el7.src.rpm
...
Finish: creating root cache
Finish: chroot init
INFO: Installed packages:
Start: build phase for acl-2.2.51-12.el7.src.rpm
Start: build setup for acl-2.2.51-12.el7.src.rpm
warning: Could not canonicalize hostname: 3618f6f8c0bf49a9a47c250db521df79
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/acl-2.2.51-12.el7.centos.src.rpm
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.
No such …
```

fix defaults for yum_builddep_opts (it is list)

---

py/mockbuild/plugins/compress_logs.py
py/mockbuild/plugins/package_state.py

To be more consistent. So, we can do now smth like
```
mv tmp_dir/*.log log_place/build_id/
```
from #38

rename package_state plugin's log to have .log suffix

---

py/mockbuild/package_manager.py

When yum-utils commands are suffixed with `-deprecated`, they should be used instead. In addition, `dnf repoquery` should be used with dnf.

Fix calls of yum-builddep and repoquery, and use 'dnf repoquery' for dnf

---

py/mockbuild/backend.py

Now that we always use `bash --login` (after 826c9d6), we have to always
quote the macro. Fixes the regression noted in
https://bugzilla.redhat.com/show_bug.cgi?id=1450516#c12.
---
Untested; though seems right by inspection.

backend.py: quote check_opt

---

py/mockbuild/util.py

On Oracle Linux EL7 platform, systemd-nspawn execution was was failing due to unsupported '-a' parameter being passed. This change adds detection for the 'ol' platform to implement the '-a' workaround for systemd-nspawn on Oracle Linux systems.

Add detection of OL (Oracle Linux) distribution

---

py/mockbuild/scm.py

There are cases when people do %include %{SOURCE1}.
For example, grub2 package in Fedora has:
...
Source7:	grub.patches
...
%include %{SOURCE7}
...
In that case mock-scm fails with:
error: Unable to open /builddir/build/SOURCES/grub.patches: No such file or directory
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

scm: define _sourcedir to checkout directory

---

etc/mock/mageia-cauldron-armv5tl.cfg
etc/mock/mageia-cauldron-armv7hl.cfg
etc/mock/mageia-cauldron-i586.cfg
etc/mock/mageia-cauldron-x86_64.cfg

Mageia 6 is released and branched from Cauldron now.

mageia-cauldron: Change releasever to 7

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/plugins/ccache.py

When using nspawn /tmp gets over-mounted with tmpfs. Let's use different
directory for our ccache bind mount.

ccache: use different bind mount directory

---

mock/py/mockbuild/buildroot.py

In case one overrides the rootdir option and the rootdir is located
outside of basedir, it was not cleaned up when calling --clean.
Fix this case by checking if the rootdir is outside basedir. If that
is the case, run an extra rmtree() on it.
Fixes #90

Delete rootdir as well when calling clean

---

mock/py/mockbuild/util.py

DeskOS (http://deskosproject.org) uses mock to build packages.
We need to add this check, unless there is a generic way to test for an EL fork.

Add support for DeskOS

---

mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

Fix for #130
Change the previously hardcoded value for chrootgroup to be
a configuration file option which defaults to the previous
hardcoded value.
Signed-off-by: Mark D Horn <mark.d.horn@intel.com>

Enable chrootgroup as a config file option

---

mock/py/mockbuild/mounts.py

Fixes an issue where a failed build can result in mountpoints left around causing subsequent builds to fail.
e.g. `/var/lib/mock/epel-7-x86_64/root/var/cache/yum`(`/`).
`ismounted()` currently returns `False` because the trailing slash does not appear in `/proc/mounts`
Removing the trailing slash from `config_opts['plugin_conf']['yum_cache_opts']['target_dir'] = "/var/cache/%(package_manager)s/"` also works around the issue.

Strip trailing / from mountpath in ismounted()

---

mock/py/mockbuild/plugins/tmpfs.py

In some instances, proc/sys/fs/binfmt_misc would end up not getting
cleaned up correctly. Adding -R to the unmount lines fix it for me.

use recursive unmount for tmpfs

---

mock/py/mockbuild/util.py

This is for #8. All stderr output lines are prefixed by 'BUILDSTDERR:'. Also, all lines started with '+' are skipped (rpm debug output)

Splitting stdout and stderr in build.log

---

mock/py/mock.py
mock/py/mockbuild/plugins/bind_mount.py
mock/py/mockbuild/plugins/mount.py

Its supposed to be a minimal buildroot just for running the package
manager, so don't try to mount things into it.

Don't setup mounts in the bootstrap buildroot

---

mock/py/mockbuild/mounts.py

Previously, mock assumed that essential mounts are never mounted when
mock starts up. That's not true, as multiple non-destructive mock
processes are allowed (`--shell`, `--install`, etc.) to run
concurrently. So when you use `mock --shell` and do a `mock --install`
in parallel, it breaks your shell, because it unmounts its proc.
This improves the situation by first asking whether the mounts aren't
there already.

Detect if essential mounts are already mounted

---

mock/etc/mock/site-defaults.cfg

The example added for config_opts['plugin_conf']['sign_opts']['opts'] in
3c2de6a ("Add a plugin that calls command (from the host) on the
produced rpms.", 2015-04-17) was missing a trailing quote in the
_gpg_path definition.  Users who failed to notice this when uncommenting
the option receive an error when building packages:
Unexpected EOF missing '"'
Reported-by: Phil Wyett <philwyett@kathenas.org>
Signed-off-by: Todd Zullinger <tmz@pobox.com>
https://bugzilla.redhat.com/show_bug.cgi?id=1537797

site-defaults: fix quoting in sign_opts example [RHBZ#1537797]

---

mock-core-configs/etc/mock/epel-6-x86_64.cfg
mock-core-configs/etc/mock/epel-7-x86_64.cfg

EPEL now allows packages to use 'devtoolset*' packages from the SCLo and
SCLo-rh repositories as BuildRequires.  Restrict the package list from
the SCLo repositories to 'devtoolset*' with the includepkgs option.
These repositories are currently only available for x86_64.  aarch64 and
ppc64le are in testing now in CentOS¹.
¹ https://bugs.centos.org/view.php?id=14078

mock-core-configs: add CentOS SCL repositories to EPEL 6 & 7 (x86_64)

---

mock/py/mockbuild/util.py

After commit https://github.com/rpm-software-management/mock/commit/a40567a635ad3a76f480198a499931eab6aabbdd mock-scm would clone the sources in the current directory instead of in the temp directory it was expecting. This is because nspawn is not used when `chrootPath` evaluates to false (even when `USE_NSPAWN` is true) and `ChildPreExec.__call__` only checks to see if `USE_NSPAWN` is set before running `condChdir(self.cwd)`.
This PR addresses this issue.

Honor the "cwd" flag when nspawn is being used and "chrootPath" is not

---

mock/py/mockbuild/plugins/chroot_scan.py

Calling this plugin for 'initfailed' event is useful e.g. when one wants to collect dnf logs in case repo sync failure when buildroot is being initialized.

invoke chroot scan for 'initfailed' event

---

mock/docs/mock.1
mock/etc/bash_completion.d/mock
mock/etc/mock/site-defaults.cfg
mock/py/mock.py
mock/py/mockbuild/plugins/overlayfs.py
mock/tests/15-overlayfs-layers.tst
mock/tests/overlayfs_layers_test.py

This new plugin implements mock's snapshot functionality using overlayfs. From user perspective it works similar to LVM plugin, but unlike LVM plugin, it only needs directory (not a volume group) for it's  data (snapshots). Plugin has no aditional dependencies, it only requires kernel with overlayfs support, but this is the case for both current Fedora and RHEL-7.
For more more information, see detailed description in plugin file:
mock/py/mockbuild/plugins/overlayfs.py

overlayfs - new snapshot plugin

---

mock/tests/functions

As I have been adding test (my other pull request), I have noticed, there is a bug in runcmd function in mock/tests/functions file [1]. It currently runs sh with 'ret' env. variable set to 'time'. Then variable 'ret' is  not set, when next line (with return) is executed.  Also time command is not ran and bug causes test to fail when using: set -u.
I have made a change to make it work in a way as was (probably) originaly intended.

mock/tests/functions: fixed runcmd function

---

mock/py/mockbuild/plugins/bind_mount.py

If you did wanted to create file in your mount it crashed. This creates empty file where will be copied that file.

add binding in config file for file

---

mock-core-configs/etc/mock/opensuse-leap-15.0-x86_64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-aarch64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-i586.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64le.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-x86_64.cfg

This PR adds initial targets for building for openSUSE Leap 15.0 and Tumbleweed.
This depends on https://github.com/xsuchy/distribution-gpg-keys/pull/13

Add initial openSUSE distribution targets

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

I have a project (https://github.com/nhorman/freight) which requires that some commands be run as the root user.  unfortunately, mock is not currently able to run commands as uid/gid 0 / user name root.  This set of patches enhances mock such that the uid/gid/username can be set in the config at build time.  Teste successfully by myself building freight container rpms
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Allow root

---

mock-core-configs/etc/mock/mageia-cauldron-aarch64.cfg

The armv5tl architecture has been replaced with aarch64 in Cauldron, as Mageia is bootstrapping an AArch64 variant for Mageia 7.

Replace armv5tl with aarch64 for Mageia Cauldron

---

mock/py/mockbuild/package_manager.py
mock/py/mockbuild/plugins/package_state.py
mock/py/mockbuild/util.py

You have to add to config:
Determining path to MicroDnf:
config_opts['microdnf_command'] = '/usr/bin/microdnf'
Command on install with MicroDnf:
config_opts['microdnf_install_command'] = 'microdnf install'
MicroDnf cannot use source config at /etc/microdnf/. At this moment, MicroDnf uses source config of Dnf, but its structure is already prepared for moment, when it will be available. Also, MicroDnf can't use installroot and builddep params. You need to use Dnf for these options.

WIP: Added support for MicroDnf

---

mock/docs/mock.1
mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

Mock has disabled networking by default since be4b13a ("Add
"rpmbuild_networking" key (False by default) for nspawn backend",
2015-07-27).  When using a systemd-nspawn chroot (the default), the host
resolv.conf is copied to the container by nspawn when 'use_host_resolv'
is True, which causes spurious network timeouts as noted in
RHBZ#1514028.
When the variable is unset, mock avoids populating it since 3f93978 ("do
not populate /etc/resolv.conf when networking is disabled
(RHBZ#1514028)", 2018-05-30).
Disabling 'use_host_resolv' by default provides a better out-of-the-box
experience.  The variable will be enabled when '--enable-network' option
is used, similar to the 'rpmbuild_networking' variable.
This is a follow-up to #190.

Disable use_host_resolv by default

---

mock/mock.spec

Prior to this change, the rpm build process would replace all single `@` characters in the man pages with the version number.
The problem is that Perl treats `@VERSION` as an (undefined) array, so the regex matcher is simply `@`.
Escape the two `@` characters so we match the literal string `@VERSION@`
in the man page nroff sources.

fix @VERSION@ processing in man pages

---

mock/etc/bash_completion.d/mock

I hit the issue of `--nocheck` causing subsequent completion to be broken again yesterday and decided to take a look at fixing that.  In the process I found a small handful of options which were not being completed and some others which completed directories but should also provide completion for files.
While I was here, I tried to lightly modernize the completion using features from newer bash-completion releases. All supported Fedora/RHEL releases have versions of bash-completion with the necessary functions.
I tried to test and verify that all completions work as well or better after these changes, but more testing is always a good thing.

Completion improvements

---

mock/py/mockbuild/util.py

Locale en_US.UTF-8 is not guaranteed to be available. It may be in optional, not installed by default langpack, or may need to be generated.
Instead, use C.UTF-8. It is available in glibc for 3 years already, even longer in Debian (courtesy of local patch).

fallback to C.UTF-8 locale

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

When building the kernel with mock on gitlab CI, I found that there was no way of having it print the output. Digging into the code, I found that `print_main_output` was the main thing controlling whether or not I saw the logs.
This PR simply exposes that configuration value in the actual configs. The default behaviour is preserved; it will detect whether stderr is a tty, and set it True or False based on that. However, it can now be overridden by the configuration.

expose print_main_output in configs

---

mock/py/mock.py

Since commit 3a9221c5d13, a rebuild with scm in the config options
would a) check out from SCM b) generate an SRPM from spec and sources
c) clean up the SCM checkout including the spec file
d) try to copy the spec into the chroot

Don't try to use a spec we've already cleaned up

---

mock/py/mockbuild/exception.py
mock/py/mockbuild/package_manager.py

Created a new exception for absent weak dependent package.
Added custom message for error caused by dnf-utils not being installed.
bugzilla url:
https://bugzilla.redhat.com/show_bug.cgi?id=1626879
I am an intern working under Mirek Suchý.

[mockbuild] create custom error message for dnf-utils not being installed

---

mock/mock.spec

Fedora 29 does not ship with by yum default, so require dnf-utils to allow non-bootstrapped epel-7 builds on Fedora without needing to manually install yum/dnf-utils.

Require dnf-utils

---

mock/py/mockbuild/util.py

Fixes traceback:
File "/usr/lib/python3.7/site-packages/mockbuild/plugins/root_cache.py", line 42, in __init__
self.decompressProgram = self.root_cache_opts['decompress_program'] or self.compressProgram
KeyError: 'decompress_program'
Complements: 2b4d3809821de8590689e3a5315ee465711c44dd

config['decompress_program'] default

---

mock/docs/mock.1

The config file option is rpmbuild_networking not rpmbuild_network

Fix --enable-network documentation in man page

---

mock-core-configs/etc/mock/mageia-7-aarch64.cfg
mock-core-configs/etc/mock/mageia-7-armv7hl.cfg
mock-core-configs/etc/mock/mageia-7-i586.cfg
mock-core-configs/etc/mock/mageia-7-x86_64.cfg
mock-core-configs/etc/mock/mageia-8-aarch64.cfg
mock-core-configs/etc/mock/mageia-8-armv7hl.cfg
mock-core-configs/etc/mock/mageia-8-i586.cfg
mock-core-configs/etc/mock/mageia-8-x86_64.cfg
mock-core-configs/etc/mock/mageia-cauldron-aarch64.cfg
mock-core-configs/etc/mock/mageia-cauldron-armv7hl.cfg
mock-core-configs/etc/mock/mageia-cauldron-i586.cfg
mock-core-configs/etc/mock/mageia-cauldron-x86_64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.0-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-x86_64.cfg

This PR adds new Mageia 7 and openSUSE Leap 15.1 configs, as well as adding in openSUSE Leap AArch64 configs for targeting that platform.

Add new Mageia and openSUSE configs

---

mock/py/mockbuild/util.py

Many paths in mock are a combination of a directory sepcified in
configuration with a subdirectory read in from the filesystem (or
specified on the commandline or from some other system service).  The
configuration paths were made into text strings by the Jinja2 templated
configs feature.  On python2 (el6 and el7) the strings from the
filesystem are byte strings.  When the two string types are combined, a
UnicodeError is thrown.
Rather than find all the places where mock is loading byte strings and
would need to transform them back into text strings, this patch merely
changes the text strings returned from Jinja2 into native strings (ie:
text strings on python3 and byte strings on python2).  This should
restore the behaviour of the pre-Jinja2 configuration.
To reproduce the error that …

Fix mock for non-ascii paths on python2

---

mock/py/mockbuild/util.py

I found an odd behavior when running nspawn.  Being able to see the exact nspawn arguments was helpful in diagnosing my issue (missing capability).  I figured this would be helpful to others too.

Add debug logging for systemd-nspawn and related args

---

mock-core-configs/etc/mock/opensuse-tumbleweed-aarch64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-i586.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64le.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-x86_64.cfg

The DistTag macro definition for openSUSE Tumbleweed was slightly
incorrect, and did not correctly retrieve the `VERSION_ID` from the
`os-release(5)` file due to how shell expansion works.
This should be fixed now.

Fix openSUSE Tumbleweed DistTag definition

---

mock-core-configs/etc/mock/fedora-28-armhfp.cfg
mock-core-configs/etc/mock/fedora-29-armhfp.cfg
mock-core-configs/etc/mock/fedora-30-armhfp.cfg
mock-core-configs/etc/mock/fedora-rawhide-armhfp.cfg
mock-core-configs/etc/mock/mageia-6-armv5tl.cfg
mock-core-configs/etc/mock/mageia-6-armv7hl.cfg
mock-core-configs/etc/mock/mageia-7-armv7hl.cfg
mock-core-configs/etc/mock/mageia-cauldron-armv7hl.cfg

There are a number of AArch64 systems that natively support
building and running code for 32-bit ARM ISAs.
In particular, some of the new ARM cloud servers are capable of it,
like the new ARM cloud servers from Packet.com.
RPM already has enhancements for supporting this as well.
So, let's go ahead and allow it.

Allow AArch64 systems to build 32-bit ARM packages

---

mock/py/mockbuild/plugins/root_cache.py

When in Python 2 (el7) mock would crash while writing `cache.log` if
yum/dnf would output any non-ascii characters.
Following is an example exception message from such a crash:
```
Start: creating root cache
ERROR: 'ascii' codec can't encode character u'\u2192' in position 88551: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/libexec/mock/mock", line 977, in <module>
main()
File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
result = func(*args, **kw)
File "/usr/libexec/mock/mock", line 766, in main
run_command(options, args, config_opts, commands, buildroot, state)
File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
result = func(*args, **kw)
File "/usr/libexec/mock/mock", line 793, in …
```

Fix crash on non-ascii dnf log messages

---

mock/py/mockbuild/util.py

The mkstemp() call creates file with 0600 permissions, and it is
not a natural setup for the /etc/resolv.conf file.
The 0600 permissions are especially problematic with
'systemd-nspawn --private-users=pick' (recommended settings by
systemd docs, and used e.g. by copr in some cases).  The option
doesn't imply that the file is re-mapped according to the picked
user namespace.
Fixes: #265

grant anyone access to bind-mounted /etc/resolv.conf

---

mock/py/mock.py
mock/py/mockbuild/package_manager.py

First, make sure that 'util.do' uses the pre-configured
Buildroot's "nspawn_args" config (when using nspawn is enabled).
Second, postpone setup_host_resolv() call after bootstrap chroot
initialization step, so the bootstrap chroot doesn't inherit
resolv.conf from the main chroot.  This is needed because the main
chroot might or might not have network disabled, while bootstrap
chroot has network always enabled.  IOW, even though both chroots
are using nspawn, the former resolv.conf might be intentionally
empty while the latter one should always be a copy of hosts's
/etc/resolv.conf.

bootstrap: independent network configuration

---

mock-core-configs/etc/mock/epel-6-x86_64.cfg
mock-core-configs/etc/mock/epel-7-aarch64.cfg
mock-core-configs/etc/mock/epel-7-ppc64le.cfg
mock-core-configs/etc/mock/epel-7-x86_64.cfg

There are several devtoolset-*-elfutils-libelf packages which
provide 'libelf.so.1()(64bit)' soname (bug), and since rpm-libs
depend on that soname those could be installed instead.
This actually happens if the bootstrap --installroot is done with
dnf (dnf-yum) package, where /usr/bin/yum calculates the
transaction a little bit differently than /usr/bin/yum-deprecated.
It's (probably?) not OK to just '--disablerepo sclo*' for
bootstrap --installroot, since those repositories are now by
default allowed even in Koji [1] and some package in that
transaction might (at least in theory) depend on some DTS package.
https://lists.fedorahosted.org/archives/list/\
epel-devel@lists.fedoraproject.org/thread/6EJIQ72JXWAAOQPFLRFYE5A7CUKC756D/

bootstrap: enforce elfutils-libelf installation in epel-*

---

mock-core-configs/etc/mock/mageia-6-armv5tl.cfg
mock-core-configs/etc/mock/mageia-6-armv7hl.cfg
mock-core-configs/etc/mock/mageia-6-i586.cfg
mock-core-configs/etc/mock/mageia-6-x86_64.cfg
mock-core-configs/etc/mock/mageia-7-aarch64.cfg
mock-core-configs/etc/mock/mageia-7-armv7hl.cfg
mock-core-configs/etc/mock/mageia-7-i586.cfg
mock-core-configs/etc/mock/mageia-7-x86_64.cfg
mock-core-configs/etc/mock/mageia-cauldron-aarch64.cfg
mock-core-configs/etc/mock/mageia-cauldron-armv7hl.cfg
mock-core-configs/etc/mock/mageia-cauldron-i586.cfg
mock-core-configs/etc/mock/mageia-cauldron-x86_64.cfg

Mageia still uses yum-style mirrorlists, and the mirrorlists are
returned in random order in each request. To make the best use of
this, we'll use fastestmirror so that somewhat fast mirrors are
selected more often.

Add 'fastestmirror=1' to Mageia mock configs

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

RPM 4.15 is there, so let's turn it on!
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

Enable dynamic BuildRequires for Fedora Rawhide

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

Run as mock -r fedora-30-x86_64 shell --old-chroot and I can see the loop0-loop11 in /dev.
Doesn't work without --old-chroot

Allow more loop devices

---

mock-core-configs/etc/mock/epel-7-aarch64.cfg
mock-core-configs/etc/mock/epel-7-ppc64.cfg
mock-core-configs/etc/mock/epel-7-ppc64le.cfg
mock-core-configs/etc/mock/epel-7-x86_64.cfg

This caused problems on aarch64 copr builders recently -- the
default baseurl failed on http error 404.

core-configs: epel-7 profiles to use mirrorlists

---

mock/py/mockbuild/buildroot.py
mock/py/mockbuild/mounts.py
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/util.py

This set of patches is sufficient for me to get mock running in a rootless container. I was testing with https://github.com/debarshiray/fedora-toolbox - but something like `podman run --privileged fedora:29` should work as well. 
(I developed and tested this against 1.4.13, then rebased to devel - I don't think anything should have broken with the rebase, but it's possible.)
The three changes are:
* Use bind mounts for device files
* Use a bind mount for /sys
* Use the %_netsharedpath RPM macro to avoid RPM trying and failing to chown /proc and /sys

Adjust buildroot creation to work inside a user namespace.

---

mock/docs/mock.1

I'm missing this part in a man page.

Mention user configuration file in a man page

---

mock/etc/mock/site-defaults.cfg
mock/mock.spec
mock/py/mockbuild/plugins/compress_logs.py
mock/py/mockbuild/plugins/procenv.py
mock/py/mockbuild/util.py

This adds a plugin similar to hw_info.  Where hw_info produces detailed output on the hardware, this dumps a significant amount of information about the build time environment, any capabilities, and much more.

Add procenv plugin for more detailed buildtime information

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

bootstrap-chroot: always explicitly install shadow-utils
Previously we only did this explicitly for yum_install_command,
apparently because yum itself (even transitively) never depended on
shadow-utils.
The 'dnf' package OTOH (mentioned in dnf_install_command and
microdnf_install_command) used %systemd_requires before.  It means that
also systemd package was installed as a dependency, and transitively
/sbin/groupadd binary (shadow-utils).  So we didn't need to mention
'shadow-utils' explicitly before.  This has changed recently in dnf [1],
so we need to explicitly install shadow-utils for both
{micro,}dnf_install_command.
Per error:
Finish(bootstrap): dnf install
ERROR: Could not find useradd in chroot, maybe the install failed?
[1] …

bootstrap-chroot: install shadow-utils by dnf as well

---

mock-core-configs/etc/mock/rhel-7-aarch64.cfg
mock-core-configs/etc/mock/rhel-7-ppc64.cfg
mock-core-configs/etc/mock/rhel-7-ppc64le.cfg
mock-core-configs/etc/mock/rhel-7-x86_64.cfg
mock-core-configs/etc/mock/rhel-7.tpl
mock-core-configs/etc/mock/rhel-8-aarch64.cfg
mock-core-configs/etc/mock/rhel-8-ppc64.cfg
mock-core-configs/etc/mock/rhel-8-ppc64le.cfg
mock-core-configs/etc/mock/rhel-8-x86_64.cfg
mock-core-configs/etc/mock/rhel-8.tpl
mock-core-configs/etc/mock/rhelepel-8-aarch64.cfg
mock-core-configs/etc/mock/rhelepel-8-ppc64.cfg
mock-core-configs/etc/mock/rhelepel-8-ppc64le.cfg
mock-core-configs/etc/mock/rhelepel-8-x86_64.cfg
mock-core-configs/etc/mock/rhelepel-8.tpl
mock-core-configs/mock-core-configs.spec
mock/py/mock.py
mock/py/mockbuild/util.py

Try e.g. on Fedora:
Register:
```
$ subscription-manager register (--serverurl subscription.rhsm.stage.redhat.com) \
--username username \
--password password
```
Check available pools:
```
$ subscription-manager list --all --available
...
Pool ID:  <THE_POOL_ID>
...
```
Obtain the keypair:
```
...
$ ls /etc/pki/entitlement
<KEY_ID>-key.pem  <KEY_ID>.pem
```
And try mock:
```
$ mock -r rhel-8-x86_64 --shell
...
```

Red Hat subscription-manager support

---

mock-core-configs/etc/mock/templates/centos-8.tpl

That is alternative to CodeReady Linux Builder repo from RHEL 8.
Also move the config up in the file so it is close the other main
repositories.

centos-8: enable PowerTools repo

---

mock-core-configs/etc/mock/amazonlinux-2-aarch64.cfg
mock-core-configs/etc/mock/amazonlinux-2-x86_64.cfg
mock-core-configs/etc/mock/templates/amazonlinux-2.tpl

This PR adds amazon linux 2 config files with references to gpg keys provided by this [PR for distribution-gpg-keys](https://github.com/xsuchy/distribution-gpg-keys/pull/24/commits/3601e86a359892eea54e57d3e900199b9ee4ed5b).

Add Amazon Linux 2 configs

---

mock-core-configs/etc/mock/epel-6-i386.cfg
mock-core-configs/etc/mock/epel-6-ppc64.cfg
mock-core-configs/etc/mock/epel-6-x86_64.cfg
mock-core-configs/etc/mock/epel-7-aarch64.cfg
mock-core-configs/etc/mock/epel-7-ppc64.cfg
mock-core-configs/etc/mock/epel-7-ppc64le.cfg
mock-core-configs/etc/mock/epel-7-x86_64.cfg
mock-core-configs/etc/mock/mageia-6-armv5tl.cfg
mock-core-configs/etc/mock/mageia-6-armv7hl.cfg
mock-core-configs/etc/mock/mageia-6-i586.cfg
mock-core-configs/etc/mock/mageia-6-x86_64.cfg
mock-core-configs/etc/mock/mageia-7-aarch64.cfg
mock-core-configs/etc/mock/mageia-7-armv7hl.cfg
mock-core-configs/etc/mock/mageia-7-i586.cfg
mock-core-configs/etc/mock/mageia-7-x86_64.cfg
mock-core-configs/etc/mock/templates/centos-8.tpl
mock-core-configs/etc/mock/templates/fedora-29.tpl
mock-core-configs/etc/mock/templates/fedora-30.tpl
mock-core-configs/etc/mock/templates/fedora-31.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl

This is a follow-up for PR#342
At the moment of creating this commit, all Fedora configs works
and it is possible to build in them using the podman image.
Both EPEL 6 and 7 works too, but there is no available image for
EPEL 8 yet. I've configured it though in order to have it prepared
once the image is ready.
Neither Mageia 6 nor 7 works properly. Mageia 6 fails with DNF
traceback and Mageia 7 fails because of failing to sync repos.
I guess those might fix _themselves_.
I haven't modified any other mock configs because
1) Those systems don't have Dnf/Yum (cauldron, opensuse)
2) I didn't know what are the official podman images for them
(rhel, centos-stream)
3) It just didn't work and failed with traceback
(amazonlinux, openmandriva-cooker)

configure podman containers for Fedora, EPEL and Mageia

---

mock/etc/mock/site-defaults.cfg
mock/mock.spec
mock/py/mock.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/plugins/root_cache.py
mock/py/mockbuild/util.py

Running mock for the latest distro on an old one doesn't always work mainly
due to a new compression format or a new checksum algorithm. Using the image
skips the installation step and allows using the latest runtime directly.
To turn this feature on, add following to the config file:
config_opts['use_bootstrap_image'] = True
You can also override image tag (defaults to 'fedora:latest'):
config_opts['bootstrap_image'] = 'fedora:latest'

Use podman to pull and export an image as a bootstrap chroot.

---

mock/py/mockbuild/backend.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/plugins/package_state.py

This reverts commit 92aaabe44824bb2bd95792dcf4b80767ba30d24a and part of
commit a239b59b871c8cf2a74e23cfa2335012b50d1181.
Fixes: #341, #322 (corrected fix), rhbz#1751944

don't play with uid_manager unnecessarily

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

proposed solution for https://github.com/rpm-software-management/mock/issues/309

ignore ./var/log when creating root_cache - fixes #309

---

mock/py/mockbuild/plugins/hw_info.py

We don't mind if the tools in hw_info plugin are called as root or not
(both ways would work well) but since root-owned hw_info.log file
causes problems on NFS mounts, and to not overcomplicate things, it is
better to drop the privileges around the whole logic in hw_info plugin.
Fixes: #85

hw_info: don't create root-owned files

---

mock/py/mock.py
mock/py/mockbuild/util.py

On Red Hat systems, the qemu-user-static package provides
/usr/bin/qemu-x86_64-static on all architectures.  If that file is
missing => the whole package is missing => and the feature can not work.
Also, we don't support --forcearch through --bootstrap-chroot ATM.

mock: detect that forcearch can not work

---

mock/py/mockbuild/plugins/selinux.py

The /sys/fs/selinux mountpoint is by definition essential mount, and we
basically need to overmount it before we execute package manager.  Nb.,
see the original commit b8b721b76adb7ed7338066e6cb4f6a091b5fc675.
See also: fa1ddc50cf4ae86cdada5d2f539f4d2d3e3bca50
Fixes: rhbz#1756972

mock: selinuxfs && nspawn once more

---

mock/py/mock.py
mock/py/mockbuild/backend.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

To fix --install* options for bootstrap transparently, all the files
given on command-line need to be bind-mounted into bootstrap chroot so
they can be processed _inside_.
Since the files on command-line may be relative to cwd and we don't want
to create arbitrary directory structures within bootstrap buildroot, we
simply bind-mount the files into "home" directory.  The obvious
consequence is that multiple files with the same basename could clash
inside in the homedir, so we rather raise an error as soon as possible
instead of overmounting the same path.
Fixes: rhbz#1447627

bootstrap: fix --install and --installdeps

---

mock/docs/mock.1
mock/py/mock.py

While we are on it, drop ownership note in manual page (after
5df0a075ee5a the requirement is dropped).
Fixes: #375

chain: raise error for --localrepo without --chain

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

Now it is enough to set 'compress_logs_enable' to True, and the plugin
should work (it has some defaults).  It is now even useless to require
users to set 'compress_logs_opts' to {} first, so drop that instructoin
from site-defaults.cfg.

compress_logs: setup defaults to 'gzip'

---

mock/docs/mock.1
mock/py/mock.py
mock/py/mockbuild/backend.py

Fix #351
The `Commands.scrub` method requires `bootstrap_chroot` object initialized
in order to work with it. I.e. it doesn't scrub a bootstrap chroot unless
the `--bootstrap-chroot` parameter is set. Creating its own object inside
the method would duplicate a lot of existing code and doing it without the
object and its methods and properties is IMHO not a good idea.
Since the workaround for the #351 is
mock -r <chroot> --bootstrap-chroot --scrub=all
we can just simply fix our parser to pretend like `--bootstrap-chroot`
was set, when using `--scrub`.

scrub bootstrap chroot accordingly

---

mock/py/mockbuild/buildroot.py

When we didn't create the directory first, the tolerant chown in
self.uid_manager.changeOwner ignored non-existent directory.  Later we
created the directory in mkdirs(builddir/SPECS) request anyways, but
we didn't change the owner anymore.
Reproducer:
$ touch empty.spec
$ mock --scrub=root-cache --scrub=chroot && mock -n --buildsrpm --spec=empty.spec --sources=.
...
PermissionError: [Errno 13] Permission denied: '/var/lib/mock/.../root/builddir/build/SOURCES'
Fixes: rhbz#1694420

buildroot: pre-create builddir before changing it's owner

---

mock-core-configs/etc/mock/opensuse-leap-15.0-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.0-x86_64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-x86_64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-aarch64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-i586.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64le.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-x86_64.cfg

bootstrap: drop shadow-utils from dnf_install_command for opensuse chroots

---

mock/py/mockbuild/backend.py

There's separate '--scrub=bootstrap' option, or '--scrub=all' for that,
but '--cleanup' semantics is to cleanup buildroot only (and not to
invalidate cached bootstrap).

clean: don't clean bootstrap chroot

---

mock/py/mockbuild/package_manager.py

```
$ mock -r epel-6-x86_64 --scrub=all
$ mock -r epel-6-x86_64 --bootstrap-chroot --shell
...
ERROR: Command failed:
```

bootstrap: create gpg key directory before copying there

---

mock-core-configs/etc/mock/fedora-31-i386.cfg
mock-core-configs/etc/mock/fedora-rawhide-i386.cfg

Those configs don't have more repos, so the cost override doesn't make
sense.

configs: drop cost=2000 from fedora-31+-i386

---

mock/py/mockbuild/util.py

Fix bug caused c3656c74477b22b3cc8dd8d, but we should define clearly
behavior of --shell/--chroot.

do_with_status: don't break string into list of characters

---

mock-core-configs/etc/mock/templates/rhel-7.tpl
mock-core-configs/etc/mock/templates/rhel-8.tpl
mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/util.py

We copy the gpg keys from host nowadays, and after 63ab868920e8c0 for
all bootstrap chroots (not only in bootstrap image case).
So make the '<PKGMANAGER>_install_command' config options simpler, and
lower repo-prerequisites (no need to have distribution-gpg-keys in
repository)
Complements: 63ab868920e8c0
Fixes: #380, #308

bootstrap: don't install distribution-gpg-keys pkg

---

mock-core-configs/etc/mock/opensuse-leap-15.0-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.0-x86_64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-x86_64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-aarch64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-i586.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-ppc64le.cfg
mock-core-configs/etc/mock/opensuse-tumbleweed-x86_64.cfg
mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

We don't actually need the mockbuild user in bootstrap, so stop doing
useradd (etc.) and drop 'shadow-utils' from *_install_command config
option.  This speeds the installroot transaction a bit, but also
the opensuse chroots don't have this package, so we needed to override
the configs before.
Relates: #395

bootstrap: don't install shadow-utils

---

mock/py/mockbuild/plugins/lvm_root.py
mock/py/mockbuild/util.py

Seems like lvm2 started to produce unexpected stderr output:
/dev/sda: open failed: No medium found
So ignore the stderr, and parse only stdout.
Resolves: rhbz#1762728

lvm_root: fix volume removal in --scrub

---

mock/py/mockbuild/util.py

If we want call directly function util.update_config_from_file, we need set
config_paths, so config_paths should set in setup_default_config_opts,
is better than in function load_config

Initialize config_paths in funtion util.setup_default_config_opts 

---

mock/py/mockbuild/util.py

We previously allowed only one level of jinja expansion.  This is not
enough nowadays after the "jinjification" series of commits starting
with 559516800938.
E.g. hw_info plugin initialization seemed to triggered problems (#422)
by accessing (and mkdir) self.buildroot.resultdir.  That property is
defined like:
buildroot.resultdir = config['resultdir'] % config
while the related jinja values look like (for fedora-rawhide-x86_64):
'resultdir'   => '{{basedir}}/{{root}}/result'
'root'        => 'fedora-rawhide-{{ target_arch }}''
'target_arch' => 'x86_64'
so with the single-level expansion the buildroot.resultdir was
e.g. '/var/lib/mock/fedora-rawhide-{{ target_arch }}'.

mock: re-render jinja in configuration

---

mock/py/mock.py

Previously we re-used the same tarball from
/var/cache/mock/<chroot>-bootstrap/root_cache/ for initializing both
bootstrap chroot and normal chroot.

bootstrap: root_cache: deepcopy the plugin_conf options

---

mock/py/mockbuild/buildroot.py

When we still have a root uid, before 'uid_manager.__enter__' call.
Complements: 712fe3c3257bbf2bd0e60cc9d8ca2c177a05afa2

mock: create builddir on proper place

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/package_manager.py

Fixes #233.
From commits:
```
1) More careful package management choice
Previously we only warned when 'dnf' was expected for chroot
initialization, but wasn't available.  Now we detect this situation also
for other package managers (e.g. missing /bin/yum, etc.).
When installing bootstrap chroot, we aren't anymore that much picky
about host pkg manager.  This means that '/bin/yum' doesn't have to be
installed at all on host to install yum-based bootstrap, but more
importantly '/bin/dnf' doesn't have to exist on YUM based hosts when
installing DNF based chroots.  This should demotivate users from using
'--yum' option on YUM based options to install bootstrap (#233).
2)  Detect '/bin/yum' symlink to 'dnf'
In such case we actually talk to 'dnf', and it doesn't make any sense to
instantiate …
```

Fix package manager decisions

---

mock/py/mock.py
mock/py/mockbuild/plugins/lvm_root.py
mock/py/mockbuild/util.py

config: turn ON the jinja rendering a bit earlier
We need to turn on the jinja rendering before we call the
set_config_opts_per_cmdline() function because some code there might
easily want to read some config option with not-yet-rendered value.
For example, we were bitten by the 'cleanup_on_success' decisions in
set_config_opts_per_cmdline(); the check [1] whether resultdir resides
below basedir gave us wrong answers because it worked with wrong data:
resultdir = {{basedir}}/{{root}}/result
rootdir   = /var/lib/mock/fedora-rawhide-{{ target_arch }}
.. and the result was that for successful build we removed the basedir
together with resultdir containing successfully built RPMs.
[1] https://github.com/rpm-software-management/mock/blob/\
7a3bdb2fd135eefb04d74ef1db34eeedad1a16a2/\ …

jinja earlier

---

mock/py/mockbuild/podman.py

That attribute is used for 'host -> bootstrap' installation, not for
'bootstrap -> bootstrap'.
Fixes: #437

mock: don't use buildroot.pkg_manager in podman

---

mock/py/mock.py
mock/py/mockbuild/util.py

So the configuration is respected, and the obsoleted options
--old-chroot and --new-chroot still work.

don't override defaults for USE_NSPAWN

---

mock/py/mockbuild/buildroot.py

Currently mock --chain allocates 3 FDs per build and doesn't release them, making it able to run build ~300 times. This releases them prior to the next build being executed, keeping FD use ~constant.

mock: release allocated FDs in mock --chain

---

mock/py/mockbuild/rebuild.py

Right now, the `--no-cleanup-after` command line switch is ignored if `--postinstall` is also specified.

do not ignore cleanup_on_success when post_install is True

---

mock-core-configs/etc/mock/epel-6-i386.cfg
mock-core-configs/etc/mock/epel-6-ppc64.cfg
mock-core-configs/etc/mock/epel-6-x86_64.cfg
mock-core-configs/etc/mock/templates/epel-6.tpl

The indent broke dnf, and 'basearch' config option doesn't exist.
Complements: 564552e441afca0b6dcca651ff7f868421ccbafd

mock-core-configs: fix epel-6.tpl config bug

---

mock-core-configs/etc/mock/epel-6-ppc64.cfg

There's no ppc64 mirror working for centos-6 nowadays.
Relates: #452

configs: drop long time useless epel-6-ppc64

---

mock/py/mock.py
mock/py/mockbuild/util.py

We can not use `--pipe` globally to not break interactive shell in
--shell mode.  So with new systemd-nspawn mimic the behavior of old
systemd-nspawn.
Complements: b1b5730c6d584f98abc901693c547d7d0910e92b
Relates: #432
Fixes: #459

nspawn: better handle --console=pipe

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

.. again, after some time.  The residual issues should be fixed now, and
the mock caches were enhanced to make this less obtrusive (PR#365).
Switching per discussion/announcement in:
https://lists.fedoraproject.org/archives/list/\
buildsys@lists.fedoraproject.org/thread/XHTQD4AAAEGPTDPQ2TCGXUCY3MAC52G2/

mock: use_bootstrap_container=True default

---

mock/py/mockbuild/backend.py

It is kind of strange to use returnOutput=True here when we don't
actually use the output in caller, but this parameter also causes that
the raised exception (in case of command failure) contains both stderr
and stdout.  As a result, mock ends with very clear error:
/usr/bin/systemd-nspawn -q -M 0f25244d38ab4d32a46a109813628224 -D
... all the nspawn args ....
/bin/rpm -Uvh --nodeps /builddir/build/originals/python-copr-1.100-1.git.36.dff5221.fc31.src.rpm
error: Missing rpmlib features for python-copr-1.100-1.git.36.dff5221.fc31.noarch:
error:  rpmlib(DynamicBuildRequires) <= 4.15.0-1
error: /builddir/build/originals/python-copr-1.100-1.git.36.dff5221.fc31.src.rpm cannot be installed
Instead of:
/usr/bin/systemd-nspawn -q -M 0f25244d38ab4d32a46a109813628224 -D
... all the nspawn args .... …

mock: print stdout/stderr if 'install_srpm' failed

---

mock/README.md
mock/docs/release-instructions.txt

This should simplify our workflow with merging devel<->master, and also
it should make the development more clear (random contributors
intuitively want to work with master branch).
Update release workflow.

maint: bump to v2.0, and declare 'master' is the main branch

---

mock/py/mockbuild/buildroot.py

do not modify argument if the file exist, but argument does not have *rpm extension.
It works now for:
--install zsh
--install mock.rpm
--install /usr/bin/time
Fixes: #474

allow --install /usr/bin/time [GH#474]

---

mock/py/mockbuild/util.py
mock/tests/test_config_templates.py

mock: 'dnf.conf' is equivalent to 'yum.conf'
Resolves: rhbz#1806039
Relates: https://pagure.io/copr/copr/pull-request/1275
Related discussions:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-4f9536de5b
https://pagure.io/koji/issue/2026
https://lists.fedoraproject.org/archives/list/\
devel@lists.fedoraproject.org/thread/IRMM6UYHRWOI3YM6IE4DTTV4YWF3J7G2/

mock: 'dnf.conf' is equivalent to 'yum.conf'

---

mock/py/mockbuild/package_manager.py
mock/tests/test_package_manager.py

Per discussion in:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-8c3f06d776
Also skip directories that do not exist, which leads to unexpected
bind-mounts.
Fixes: #480

bootstrap: bind-mount also baseurl=/absolute/dir repos

---

mock/etc/mock/site-defaults.cfg
mock/integration-tests/19-sign-plugin.tst
mock/integration-tests/functions
mock/integration-tests/prepare/README
mock/integration-tests/prepare/prepare-user.sh
mock/py/mockbuild/plugins/sign.py
mock/py/mockbuild/util.py

It is non-trivial to assure that {{ rpms }} specified in mock
configuration isn't expanded (to empty string) too early.  Proper
solution to that will take some time, so for now revert back to the
%(rpms) syntax.
We should stay compatible with %(rpms) if we decided to move to
{{ rpms }} again in future.
Add integration test for rpmsign, plus preparation script.
This reverts commit d44ec018b59822c8ba6dcffb0002148b57a69457.
Fixes: #476, rhbz#1806577

sign-plugin: use %(rpms) variable expansion again

---

mock/tests/test_config_templates.py

The test was not gathered by test runner before.

tests: typofix in test name

---

mock/integration-tests/20-lvm-plugin.tst
mock/integration-tests/prepare/README
mock/integration-tests/prepare/prepare-lvm.sh
mock/py/mockbuild/plugins/lvm_root.py

Remove one old hack that tried to secure the chroot root mount point
re-mounted into bootstrap.  This isn't needed nowadays because we
always pre over-mount that directory by tmpfs with private flag, so
there's no risk that umount in bootstrap will also umount the main mount
point.
This commit complements 4658933b12f405681b29a3fbda224a499511810e,
b87244a88f39d856f303732eca09434a6d9da4c6 and friends.
Fixes: rhbz#1805179

lvm_root: drop hack related to bootstrap

---

mock/py/mockbuild/backend.py

That invalidates mount points, and probably cleans the buildroot too
much without reason.  There's automatic buildroot.clean() call before
each package anyways.
Fixes: #479

mockchain: don't run buildroot.finalize() for each package

---

mock-core-configs/etc/mock/opensuse-leap-15.0-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.0-x86_64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-aarch64.cfg
mock-core-configs/etc/mock/opensuse-leap-15.1-x86_64.cfg
mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl
mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/util.py

OpenSUSE uses different pattern for ssl trusted CAs from Fedora, and to
actually make dnf (or rather transitively curl) inside bootstrap chroot
work we need to install the bundle onto
'/var/lib/ca-certificates/ca-bundle.pem'.
Fixes: #500
Supersedes: #509

opensuse: copy ssl ca bundle to correct chroot path

---

mock/integration-tests/13-mockchain-gen-br.tst

tests: add 13-mockchain-gen-br.tst
Test that mockchain works, with tmpfs plugin ON (keep_mounted=True),
nocache plugin ON, and dynamic buildrequires package.
Relates: #482, #512, #479

New mockchain test

---

mock/py/mockbuild/buildroot.py

In doChroot we do the same, before we call host's rpm against chroot
rpmdb.  We need to do the same in all_chroot_packages().  This caused
problems on EL7 when building packages dynamic BuildRequires in new
chroots (Fedora 31+):
ERROR: Command failed:
Very likely we'll have to invent new doChroot()-like abstraction to
automatically call such RPM commands either from host (bootstrap
disabled) or from bootstrap chroot (bootstrap enabled), issue #525.

Cleanup rpmdb before determining installed packages

---

mock-core-configs/etc/mock/templates/centos-8.tpl
mock-core-configs/etc/mock/templates/centos-stream.tpl

This repository is disabled by default because we should offer
equivalent repository sources to RHEL by default and there is no
guarantee on the usability of the content shipped here.
In addition, a trivial commit adding the PowerTools source repo
(disabled like other source repos) has been included for completeness.
Fixes #537.

Add the Devel repo for CentOS 8 and CentOS Stream

---

mock/integration-tests/001-orphanskill-explicit.tst
mock/integration-tests/05-orphanskill-std.tst
mock/integration-tests/daemontest.c
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/util.py

Some packages may keep leftover processes on background after it's
installation, triggered by scriptlets.
Even though this is definitely packaging issue (bug in package) the
background processes keep using the chroot's root filesystem and refuse
us to umount the filesystem later (e.g. when tmpfs is enabled).
Since the dnf commands are not run under systemd-nspawn (when bootstrap
is disabled), we need to add new option which ignores the USE_NSPAWN
flag.
Fixes: #183

Call orphansKill also "postyum" time

---

mock/etc/mock/site-defaults.cfg
mock/py/mockbuild/util.py

And ignore host's configuration.  Users still can set this explicitly
in "config_opts['environment']['LANG']" when needed.
Drop 'TZ' from site-default.cfg, it isn't set in util.py anymore.
Fixes: #451

mock: default to LANG=C.UTF-8

---

mock-core-configs/etc/mock/templates/amazonlinux-2.tpl

This allows us to build against amazonlinux-2-x86_64 on Fedora host
--use-bootstrap-image.

configs: specify amazonlinux bootstrap image

---

mock/py/mockbuild/backend.py

This is mostly suggested by help(os.getlogin):
| Return the name of the user logged in on the controlling terminal of
| the process. For most purposes, it is more useful to use
| getpass.getuser() since the latter checks the environment variables
| LOGNAME or USERNAME to find out who the user is, and falls back to
| pwd.getpwuid(os.getuid())[0] to get the login name of the current real
| user id.
The motivation here is that by default, in `docker run --rm -ti
fedora:31` the call to os.getlogin() fails and user is forced to pass
the option --tmp_prefix.  The original use of getlogin() isn't well
documented and doesn't seem to be intended over getuser().  Also, there
used to be other getlogin() call in mock, but was dropped for the
similar reasons in …

mock: use getpass.getuser() instead of os.getlogin()

---

mock-core-configs/mock-core-configs.spec
mock/docs/release-instructions.txt

We could use `Conflicts:` here instead, but mock-core-configs doesn't
seem to have any use-case without mock package, at least no Fedora
Rawhide package ATM [1] directly depends on isolated mock-core-configs.
FTR, this isn't truth vice-versa, per 66da47e2960baafb35.
[1] https://src.fedoraproject.org/lookaside/rpm-specs-latest.tar.xz

configs: declare minimal version of mock

---

mock/mock.spec

The default RHEL 7 %python3_pkgversion contains value '3', which isn't
sufficient for mock.  We actually need `epel-rpm-macros` to be installed
so the macro %python3_pkgversion is re-defined to 36.
This patch fixes builds on EL7 _host_ machines.  The presence of
`epel-rpm-macros` isn't guaranteed there by default even when EPEL 7
repo is enabled (epel-rpm-macros is "only" installed into EPEL7 minimal
buildroot).
Fixes: #545

mock: re-define %python3_pkgversion on el7

---

mock/py/mockbuild/buildroot.py

We need to be ready to catch KeyError if the getresuid() doesn't have
the corresponding /etc/passwd entry.
Also fix C&P issue, the code wanted to set kargs['user'], not
kargs['gid'].
Fixes: #571

Fix doChroot() nspawn wrapper

---

mock/py/mockbuild/backend.py

Similar to commit 1a6e49605f14137cd6e68459dbe3397addfc5588,
_show_installed_packages() trips up if host rpm cannot read the
database format used inside the chroot.
Using buildroot.all_chroot_packages() where this is already dealt with
fixes the issue and reduces code duplication while at it.
Fixes: #565

bootstrap: avoid using host rpm _show_installed_packages()

---

mock/py/mockbuild/util.py

Without 'mount' plugin on PLUGIN_LIST, any previous given configuration
in util.py is replaced with empty config (so 'dirs' dict is dropped).
Accessing "config_opts['plugin_conf']['mount_opts']['dirs']" then by
user configuration causes traceback.
Fixes: #578, #583

Fix mount.py plugin

---

mock/integration-tests/24-postinstall.tst
mock/py/mockbuild/backend.py

This is needed to allow package_manager to --postinstall the built
results to target chroot.
Fixes: #564, #580

Bindmount resultdir to bootstrap chroot

---

mock/py/mockbuild/package_manager.py

Prior to this change, we would only copy the `extracted` SSL CA certificates into the chroot. If anything ran `update-ca-trust extract` inside the chroot, this would delete our custom SSL certificates from the `extracted` directory.
Copy the entire parent directory so that `sources` and `extracted` are both present in the chroot. With this change, `update-ca-trust extract` does not wipe out the CA certificates from the chroot.
Fixes: #588

mock: copy source CA certificates

---

mock/py/mockbuild/plugins/lvm_root.py

Per discussion in PR#594, it is useless to re-call set_current_snapshot
after make_snapshot.

lvm: don't recall set_current_snapshot unnecessarily

---

mock/py/mockbuild/buildroot.py
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/util.py

This was unified before under an assumption that nobody installs any
RPMs from within the mock chroot (except for the mock bootstrap chroot
itself).
But apparently tools like lorax and dracut do this, and then they miss
the /sys and /proc directories (normally installed by filesystem.rpm).
So let's split the logic again.
Before 85d544291da we created the installation .rpmmacros inside
"basedir" which was breaking --bootstrap-chroot inside Fedora Toolbox.
That was because the "basedir" isn't recursively bind-mounted below the
bootstrap chroot and thus the bootstrapped RPM failed to find the file.
Newly we create it in "rootdir" instead.
Resolves: rhbz#1848201
Reverts: 85d544291da69dbc521369c8b9b87baa3f7ffc42

Use a different .rpmmacros for install/build time

---

mock-core-configs/mock-core-configs.spec

On systems where %_pkgdocdir isn't specified or it points to versioned
directory, the docs directory looks like `../mock-core-configs-32.3/`
and we want to point user to `../mock-2.3/`.  At that build-time moment
we aren't able to tell the version of _mock_, so it is better to point
the user only to shell wild-card `../mock-*/`.
Per report in #597

Fix site-defaults.cfg reference to docs

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py
mock/tests/test_buildroot.py

It obsoletes `module_enable` and `module_install` configuration options
(still supported) but allows users to also configure "disable",
"remove", "list", and other commands.
It may or may not be useful in future, but we also execute the commands
from `module_setup_commands` as they are specified, so people can do
things like `disable foo:*` and then `enable foo:stream`.
Replaces: #586

Add `module_setup_commands` configuration option

---

mock/py/mockbuild/buildroot.py

In order to be able to successfully build images properly inside of mock
using btrfs filesystems, we need the btrfs-control device to exist.
However, we also need mock to gracefully ignore this if the host does
not support Btrfs and does not provide the btrfs-control device.

mockbuild/buildroot: Make btrfs-control available if host supports it

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/plugins/compress_logs.py
mock/py/mockbuild/plugins/showrc.py
mock/py/mockbuild/util.py

For deeper insight into what macros existed and how they were defined at build time, I added a plugin that will record the output of `rpm --showrc`.  This would be handy when trying to determine exactly what packaging macros were present in the buildroot.

Add showrc plugin to record the output of rpm --showrc

---

mock-core-configs/mock-core-configs.spec
mock/mock.spec

Since introduction of `mock-configs` virtual provides, it can happen
that mock-core-configs is not actually installed and `mock` group will
not be created.
Let put the scriptlet into separate subpackage. And together with basic
filesystem.

introduce mock-filesystem subpackage

---

mock/py/mockbuild/util.py

Print the commands we run in format which is copy-paste'able to the
commandline.

Nicer --verbose output

---

mock/etc/consolehelper/mock
mock/py/mockbuild/trace_decorator.py

When this environment variable is exported in environment, mock doesn't
go into the traceLog() logic (uses noop() tracing) - so it simplifies
the (i)pdb debugging a lot.

Accept MOCK_TRACE_LOG=false env variable

---

behave/features/auto-download-of-srpm.feature
behave/features/steps/other.py
mock/mock.spec
mock/py/mock.py
mock/py/mockbuild/backend.py
mock/py/mockbuild/util.py
mock/requirements.txt

The downloading mechanism worked before for --chain method, so move it
to a common place and reuse it for both --chain and --rebuild modes.

Auto-download the source RPMs from web with --rebuild

---

mock/py/mockbuild/buildroot.py

shutil.copy*() ignores the broken symbolic link in dst=, and simply
attempts to create the symbolic link destination file [1] and that
operation is likely to fail in mock case.
We already tried to remove the destination file, but first it was a (a)
TOCTOU way and (b) also the used os.path.exists() returns False for
broken symlinks.  So newly, let's unlink the file first without asking,
and just ignore FileNotFoundError.
[1] https://bugs.python.org/issue34374
Fixes: rhbz#1878924

Fix _copy_config() for broken symlinks in dst=

---

mock/py/mockbuild/buildroot.py

The fact that 'dst' was equivalent to 'conf_file' wasn't clear before.
The code works the same without two variables, 'dst' and 'etcdir'.

Simplify the logic of _copy_config() a bit

---

mock/mock.spec

There's nothing like cheat-filesystem, yet - and we don't want to depend
on cheat itself.
Resolves: rhbz#1887905

mock: own the cheat directory

---

mock-core-configs/etc/mock/fedora-eln-armhfp.cfg
mock-core-configs/etc/mock/templates/fedora-eln.tpl

- align repo configuration with fedora-repos-eln by switching to BaseOS and
AppStream instead of Everything
- use keys from fedora-gpg-keys rather than distribution-gpg-keys
- use explicit list of buildroot packages to install rather than comps group
- drop support for ARM

configs: ELN fixups

---

mock/py/mockbuild/backend.py

additionally, make the logging to build.log and root.log a bit better.
During the review, note that I added raiseExc=False which may not be directly visible from the diff.

do not TB if rpmbuild fails with exit code 11

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl

Without this a plenty of build dependencies are missing. At least Anaconda can't be build.
When building Anaconda I'm getting https://github.com/rhinstaller/anaconda/pull/2868#issuecomment-725525020 most of these dependencies are part of the CRB and from my understanding the CRB repository should be part of build-root which is exactly what mock is doing.
However, even with these I'm missing:
- gtk3-devel-docs
- libtimezonemap-devel
Wonder where these are...
@mmathesius could you please verify validity of this PR?

Add missing CRB repository

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl

ELN BaseOS, AppStream and CRB repositories are for runtime. However, as in RHEL there are even packages which are just in the buildroot. These packages are not part of the repositories above but only Everything repository.
So to reflect how the next RHEL will be build we should use only the Everything repository which should contain all the packages not just ones which will be shipped.
Hopefully, this should be the ultimate solution for our ELN missing packages problem. @sgallagher @mmathesius could you please do a review for me here? Thanks!
The everything repository have the missing packages required for Anaconda build.

ELN should use for build Everything repository

---

mock/py/mockbuild/plugins/sign.py

The exception raised by check_call won't be caught, and will bubble up
to mock.py - and the whole trace-back will be printed.  This isn't very
nice, though three's no exception mechanism implemented in the hook
design, and we already raise generic Exceptions in e.g. overlayfs
plugin.  NB, the RPM signing process is important enough to simply
ignore its failure.
Originally reported in:
https://pagure.io/koji/issue/2570

sign: don't ignore signing command failure

---

mock/py/mock.py

Complements 33ebacd8ce03130a8443bc28850d8c973fe891b9

mock: call buildroot.install(), not commands.install()

---

mock/integration-tests/19-sign-plugin.tst

The SIGPGP tag isn't filled nowadays, we need to use RSAHEADER.
Relates: rhbz#1902342

Fix sign plugin testsuite

---

mock/py/mockbuild/file_util.py

Print the path we've tried to call rmtree() on as well. Otherwise it's
hard to know where the faulty symbolic link even is.

file_util: Improve an error message

---

mock/mock.spec
mock/py/mockbuild/config.py
mock/py/mockbuild/text.py
mock/requirements.txt
mock/tests/test_config_templates.py
mock/tests/test_package_manager.py

I extracted this code to separate project https://github.com/xsuchy/templated-dictionary
This can be merged as soon as
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-6b516c40dc land in the stable.
If anyone is packaging mock for some distribution (other than EPEL, Fedora), please package this requirement before the next release of Mock.

use TemplatedDictionary as standalone module

---

mock-core-configs/etc/mock/templates/centos-7.tpl
mock-core-configs/etc/mock/templates/centos-8.tpl
mock-core-configs/etc/mock/templates/centos-stream.tpl
mock-core-configs/etc/mock/templates/fedora-branched.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl
mock-core-configs/etc/mock/templates/rhel-7.tpl
mock-core-configs/etc/mock/templates/rhel-8.tpl

This pull request updates Fedora, CentOS, and RHEL configs to use fully qualified paths for fetching images for setting up the bootstrap environment. Additionally, we now configure a bootstrap image for openSUSE Tumbleweed since a usable image exists now.

Update Fedora/CentOS/RHEL bootstrap images and add openSUSE Tumbleweed image

---

mock/py/mockbuild/plugins/rpkg_preprocessor.py

This option tells rpkg_preprocessor to ignore rpkg.conf and always
preprocess the spec file.  This is useful for testing mass package
changes where it's not practical to add an rpkg.conf to every package.

rpkg_preprocessor: Add a force_enable option

---

mock-core-configs/etc/mock/eol/rhel-6-x86_64.cfg
mock-core-configs/etc/mock/eol/templates/rhel-6.tpl

I've seen people complaining how hard it is to build against ELS rhel6.  While I don't
think we should encourage anyone (therefor EOL subdir), some circles will
work with EL6 for some time and this might help them.

configs: add RHEL 6 x86_64 configuration

---

mock-core-configs/etc/mock/templates/fedora-rawhide.tpl

We forgot to bump releasever in afbadca68a4d4bf304feebc98 and it is
needed because all f35 packages are being re-signed with F35 keys we are
not referencing, errors:
Public key for openssl-libs-1.1.1i-3.fc35.x86_64.rpm is not installed. Failing package is: openssl-libs-1:1.1.1i-3.fc35.x86_64
GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-34-primary, file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-34-primary, file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-33-primary
Error: GPG check FAILED

configs: fix rawhide config after branching

---

mock-core-configs/etc/mock/almalinux-8-x86_64.cfg
mock-core-configs/etc/mock/templates/almalinux-8.tpl

For now, only x86_64 is provided, but when more architectures become
available, it should be very easy to add them.
Obsoletes #703

configs: Add AlmaLinux 8 configs

---

mock/py/mockbuild/podman.py

Also use quiet mode which print just the container id.
Addressing:
Error: no container with name or ID "time=\"2021-04-15T06:18:24+02:00\" level=warning msg=\"The input device is not a TTY. The --tty and --interactive flags might not work properly\"\n0c65b4d7174ac4dc2308366b4ea0f9dc36c7533b090a98cf4d30510ae4b646cf" found: no such container
Fixes: #720

do not allocate tty for podman

---

mock-core-configs/etc/mock/opensuse-tumbleweed-s390x.cfg
mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl

openSUSE Tumbleweed has a IBM Z (s390x) port that mostly works now,
so we should have the ability to build for it.

config: Add openSUSE Tumbleweed s390x config

---

mock-core-configs/etc/mock/oraclelinux-7-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux-7-x86_64.cfg
mock-core-configs/etc/mock/oraclelinux-8-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux-8-x86_64.cfg
mock-core-configs/etc/mock/templates/oraclelinux-7.tpl
mock-core-configs/etc/mock/templates/oraclelinux-8.tpl

This PR adds configuration for building with Oracle Linux.
@Djelibeybi I was unable to find a `-latest` equivalent for the UEK repos to add to this. Is there a possibility of having one of those so that I can add optional UEK repo configuration into here? That would make it tremendously easier for people building kernel modules against UEK.

Add Oracle Linux configuration

---

mock/py/mock.py
mock/py/mockbuild/backend.py

one commit which moves code to separate function and then second commit which calls it from `install()`

allow mock --install mock --install external:*

---

mock/docs/site-defaults.cfg
mock/py/mock.py
mock/py/mockbuild/config.py

This allows packagers to count with some delay on emulated architectures. Useful in %check section.
Resolves #697

Define _platform_multiplier macro

---

mock/py/mockbuild/plugins/compress_logs.py
mock/py/mockbuild/rebuild.py

Before, errors like
Errors during downloading metadata for repository 'local'
Ended up with non-compressed logs in resultdir.
We can not easily move the 'postbuild' hook call as others already
depend on that - so I'm proposing a new hook for log processing.
Original report:
https://pagure.io/copr/copr/issue/1648

compress_logs: compress also after repo failures

---

mock-core-configs/etc/mock/templates/opensuse-leap-15.3.tpl
mock-core-configs/mock-core-configs.spec

openSUSE Leap 15.3 has multiple GPG keys and requires multiple
repositories to construct its updates.
This requires a version of distribution-gpg-keys that includes
the extra GPG keys.
Reference: https://bugzilla.opensuse.org/1186593
Requires: https://github.com/xsuchy/distribution-gpg-keys/pull/45
Requires: https://github.com/xsuchy/distribution-gpg-keys/pull/46
Fixes: #731

config: Add GPG keys and RPM repositories for openSUSE Leap 15.3

---

mock-core-configs/etc/mock/epel-next-8-aarch64.cfg
mock-core-configs/etc/mock/epel-next-8-ppc64le.cfg
mock-core-configs/etc/mock/epel-next-8-x86_64.cfg
mock-core-configs/etc/mock/templates/epel-next-8.tpl

EPEL Next is a new repository that allows packagers to build against CentOS Stream instead of RHEL.  It is not an entire rebuild of EPEL and is intended to be used in conjunction with regular EPEL.  See the [wiki page](https://fedoraproject.org/wiki/EPEL_Next) for more details.

Add epel-next-8 configs

---

mock-core-configs/mock-core-configs.spec
mock/mock.spec

This was forgotten when we created mock-filesystems
Credit goes to Orion P.
https://src.fedoraproject.org/rpms/mock/pull-request/10

move Requires of shadow-utils from mock-core-configs to mock-filesystem

---

mock-core-configs/etc/mock/templates/opensuse-leap-15.3.tpl

The GPG key path used the /opensuse/ directory for the key installed
in the /suse/ directory incorrectly.

config: Fix GPG key path for SLE updates in openSUSE Leap 15.3

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py

The system-wide versionlock from DNF does not make any sense to use for
mock builds.
Signed-off-by: Igor Raits <igor.raits@gmail.com>

Disable versionlock DNF plugin by default

---

mock/py/mockbuild/backend.py
mock/py/mockbuild/util.py

This is specific to EL7 environment, where the systemd-nspawn
implementation still doesn't support --chdir option.
Resolves: rhbz#1976702

mock: don't set --cwd for --shell when we know it fails

---

mock-core-configs/etc/mock/centos-stream-9-aarch64.cfg
mock-core-configs/etc/mock/centos-stream-9-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream-9-s390x.cfg
mock-core-configs/etc/mock/centos-stream-9-x86_64.cfg
mock-core-configs/etc/mock/templates/centos-stream-9.tpl

The composes are not signed, and at the time of writing this patch
mirrors do not exist.  Neither centos:stream9 bootstrap image exists.
Relates: #719

config: add CentOS Stream 9 "preview" configs

---

mock/py/mockbuild/plugins/lvm_root.py

... detected by Coverity:
```
Error: COPY_PASTE_ERROR (CWE-398):
mock-2.12/py/mockbuild/plugins/lvm_root.py:288: original: ""LVM Thin pool is nearly filled up ({0}%). You may experience weird errors. Consider growing up your thin pool.".format(size_data)" looks like the original copy.
mock-2.12/py/mockbuild/plugins/lvm_root.py:284: copy_paste_error: "size_data" in ""LVM Thin pool metadata are nearly filled up ({0}%). You may experience weird errors. Consider growing up your thin pool.".format(size_data)" looks like a copy-paste error.
mock-2.12/py/mockbuild/plugins/lvm_root.py:284: remediation: Should it say "size_metadata" instead?
```

lvm_root: fix copy/paste error in a warning message

---

mock-core-configs/etc/mock/templates/rocky-8.tpl

Having this enabled makes it too easy for people to accidentally
build packages that depend on content in here at runtime. That
makes it possible for people to make packages that will not be
compatible with RHEL and derivatives.
Disable this repo by default. If people need this, they can enable
it in the Mock command-line as-needed. At least then they acknowledge
what they're doing and know the consequences.
Additionally, fix the URL for the commented out "baseurl" lines, so
that they're valid.
Fixes #756

Disable the Devel repo in Rocky Linux config by default

---

mock/py/mockbuild/util.py

Use `distro.id` instead of `distro.linux_distribution`
Fixes #760

Fix use of deprecated function

---

mock-core-configs/etc/mock/eurolinux-8-i686.cfg
mock-core-configs/etc/mock/eurolinux-8-x86_64.cfg
mock-core-configs/etc/mock/templates/eurolinux-8.tpl

Hi,
I want to add EuroLinux 8 mocks. EuroLinux build roots are entire repos with all build artefacts (including lots of normally removed `-devel` packages).
I tested the following changes by building mock-core-configs with tito (--test is required) and running two builds of htop. One for x86_64 and a second one for i686.

Add eurolinux-8 x86_64 and i686 buildroots

---

mock-core-configs/etc/mock/templates/centos-stream-9.tpl

CentOS Stream 9 packages are now signed on each compose. However,
we're still in a pre-release state where CentOS Stream 9 is not yet
on the mirror network.

config: Validate GPG signatures for CentOS Stream 9

---

mock-core-configs/etc/mock/templates/almalinux-8.tpl
mock-core-configs/etc/mock/templates/centos-8.tpl
mock-core-configs/etc/mock/templates/centos-stream-8.tpl
mock-core-configs/etc/mock/templates/centos-stream-9.tpl
mock-core-configs/etc/mock/templates/oraclelinux-8.tpl
mock-core-configs/etc/mock/templates/rocky-8.tpl

This pull request makes the necessary adjustments to productionize the CentOS Stream 9 configuration. CentOS Stream 9 is now on the mirror network, so we're using the new metalinks from MirrorManager. Additionally, I've fixed an issue where weak dependencies were being installed in the build environments and synchronized the chroot setup package set with the one in Koji.

Productionize CentOS Stream 9 build configuration

---

mock/py/mockbuild/external.py

Precisely, we want to use the 'pip' or 'cargo' command from the
bootstrap chroot to install dependencies into the build chroot.
Relates: #761

Install external deps into build chroot, not bootstrap

---

mock-core-configs/etc/mock/oraclelinux-epel-7-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux-epel-7-x86_64.cfg
mock-core-configs/etc/mock/oraclelinux-epel-8-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux-epel-8-x86_64.cfg
mock-core-configs/etc/mock/templates/oraclelinux-7.tpl
mock-core-configs/etc/mock/templates/oraclelinux-8.tpl
mock-core-configs/etc/mock/templates/oraclelinux-epel-7.tpl
mock-core-configs/etc/mock/templates/oraclelinux-epel-8.tpl

There are currently no Oracle Linux EPEL configs.
Add oraclelinux-release to existing oraclelinux templates

Update Oraclelinux 7/8 configs and add Oraclelinux EPEL 7/8 configs

---

mock-core-configs/etc/mock/templates/centos-stream-9.tpl

The final production container image is now available, and all the
final URLs for example baseurls are in place too.
Also, `gpgcheck=1` at the main section breaks mockchain, so switch
to `gpgcheck=0` and set `gpgcheck=1` for each repo.
Finally, Add disabled repos for all the addon repositories so
users can consume those easily enough, since they're part of the
base CentOS Stream 9 offering.

config: Finalize CentOS Stream 9 configuration

---

mock/integration-tests/runconfigs.sh
mock/py/mock.py

Mock expects that the args.enable_disable_repos variable is set to list
of strings (dnf commandline options), not a list of pairs.
Complements: 9bdc2f1020047b9a14d72d4dc6a6aebd6dc6288a
Original-report: https://bodhi.fedoraproject.org/updates/FEDORA-2021-c0fa68d0a1

Fix broken --enablerepo option

---

mock-core-configs/etc/mock/templates/epel-8.tpl
mock-core-configs/etc/mock/templates/epel-9.tpl
mock-core-configs/etc/mock/templates/epel-next-8.tpl
mock-core-configs/etc/mock/templates/epel-next-9.tpl

The repo definitions are provided by mock-core-configs and the gpg keys are provided by distribution-gpg-keys, so epel-release/epel-next-release are not needed.  fedpkg-minimal is needed in koji for obtaining sources from dist-git and the lookaside cache, but koji installs that via the srpm-build group.
https://pagure.io/releng/issue/10369
Related #790

Reduce packages installed in epel chroots

---

mock-core-configs/etc/mock/templates/centos-stream-8.tpl
mock-core-configs/etc/mock/templates/centos-stream-9.tpl

This mimics the Koji local repo configured for Fedora configs and
allows people to emulate the build environment in CBS if needed.

configs: Add Koji local repos to CentOS Stream configs

---

mock-core-configs/etc/mock/templates/almalinux-8.tpl
mock-core-configs/etc/mock/templates/amazonlinux-2.tpl
mock-core-configs/etc/mock/templates/mageia-7.tpl
mock-core-configs/etc/mock/templates/mageia-branched.tpl

- core-configs: Update almalinux-8.tpl bootstrap_image
- core-configs: Use fully qualified bootstrap_image name

Fix `bootstrap_image` in mock-core-configs templates

---

mock/py/mock.py

If the attempt to eat "--" as the first unknown arg comes before
the handling of old-style commands, then it doesn't handle this:
mock -r something chroot -- commands
because the first unknown arg in that case is "chroot", not "--".
So we should do the old-style command handling first, *then*
check if the first unknown arg is "--" and eat it if so.
Fixes: https://bugzilla.redhat.com/2024620
Signed-off-by: Adam Williamson <awilliam@redhat.com>

argparse: handle old-style commands *before* ignoring "--"

---

mock-core-configs/etc/mock/alma+epel-8-aarch64.cfg
mock-core-configs/etc/mock/alma+epel-8-x86_64.cfg

This allows people to use AlmaLinux as the base OS for building packages
for Fedora EPEL.

config: Add AlmaLinux+EPEL configs

---

mock-core-configs/etc/mock/oraclelinux+epel-7-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux+epel-7-x86_64.cfg
mock-core-configs/etc/mock/oraclelinux+epel-8-aarch64.cfg
mock-core-configs/etc/mock/oraclelinux+epel-8-x86_64.cfg

* Rename files from `oraclelinux-epel-*` to `oraclelinux+epel-*`
* Use corresponding root name in config_opts
* Use the real EPEL

Standardize oraclelinux+epel configs

---

mock-core-configs/etc/mock/templates/centos-stream-8.tpl

Because yum (we still support EL7) does not understand it.
Resolves: BZ#2026571

2026571 - expand dnf_vars

---

mock-core-configs/etc/mock/centos+epel-7-aarch64.cfg
mock-core-configs/etc/mock/centos+epel-7-ppc64le.cfg
mock-core-configs/etc/mock/centos+epel-7-x86_64.cfg
mock-core-configs/etc/mock/centos+epel-8-aarch64.cfg
mock-core-configs/etc/mock/centos+epel-8-ppc64le.cfg
mock-core-configs/etc/mock/centos+epel-8-x86_64.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-aarch64.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-s390x.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-x86_64.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-aarch64.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-x86_64.cfg
mock-core-configs/etc/mock/templates/epel-7.tpl

The EPEL Steering Committee agreed to eliminate EPEL configs for exclusively distro+repo configs.
Additionally, fix EPEL 9 to have split configs for EPEL 9 and EPEL Next 9.

Align all the EPEL configs with the EPEL Steering Committee decision

---

mock-core-configs/etc/mock/centos+epel-7-ppc64.cfg

This was missed with the others.
Fixes: 1a1932d32607215aab694a9a655dc9bcee1434b8

config: Rename epel-7-ppc64 to centos+epel-7-ppc64

---

mock-core-configs/etc/mock/rocky+epel-8-aarch64.cfg
mock-core-configs/etc/mock/rocky+epel-8-x86_64.cfg
mock-core-configs/etc/mock/templates/rocky-8.tpl

The following configs were added to enable Rocky 8 x86_64 and aarch64 and EPEL builds:
* rocky+epel-8-x86_64
* rocky+epel-8-aarch64
The following templates were modified to disable devel-debug (which should only be enabled if a user requests as such):
* rocky-8.tpl
---
Please let me know if there is anything incorrect with the naming or the configurations in this PR. Thank you!

Config: Add rocky+epel confs + Disable devel-debug

---

mock/py/mockbuild/podman.py

bsdtar reads for /dev/st0 by default. Update the tar_cmd to explicitly specify stdin so bsdtar will work to extract podman images.
Fixes #818

mock: podman, explictily specify stdin as tar source

---

mock-core-configs/etc/mock/centos-stream+epel-9-aarch64.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-s390x.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-x86_64.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-aarch64.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-x86_64.cfg
mock-core-configs/etc/mock/templates/centos-8.tpl
mock-core-configs/etc/mock/templates/centos-stream-8.tpl
mock-core-configs/etc/mock/templates/centos-stream-9.tpl
mock-core-configs/etc/mock/templates/epel-8.tpl
mock-core-configs/etc/mock/templates/epel-9.tpl
mock-core-configs/etc/mock/templates/epel-next-8.tpl
mock-core-configs/etc/mock/templates/epel-next-9.tpl
mock-core-configs/etc/mock/templates/rocky-8.tpl

Deterministically resolve which of the "local" repositories is
the primary one:
- 'centos-stream+epel' => local is EPEL buildroot
- 'centos-stream+epel-next' => local for EPEL Next buildroot
- 'centos-stream' => local is just CentOS Stream buildroot
The only requirement is to specify the 'koji_primary_repo' variable to
'epel', 'epel-next' or 'centos-stream'.
Users may still opt-in to use '--enablerepo "local*"' if they really
want to enable all the Koji buildroots.

Resolve the multiple "local" repo problems

---

.travis.yml
mock/mock.spec
mock/requirements.txt
mock/run-tests.sh

This is breaking build on F34 (#2033331), but it also doesn't make any
sense to run coverage analysis for every RPM build.  By default, if run
locally, the ./run-tests.sh script still performs coverage analysis.

mock: don't print coverage stats for RPM builds

---

mock/py/mockbuild/podman.py

Fixes #831
Without env vars passed to the podman run command, outbound proxy doesn't work while creating the root dir

Pass env to podman run

---

mock/etc/bash_completion.d/mock

The `--scrub=bootstrap` and `--short-circuit=prep` arguments were missing from completion script.

completion: add missing args for --scrub and --short-circuit

---

mock-core-configs/etc/mock/templates/centos-stream-9.tpl
mock-core-configs/mock-core-configs.spec

The CentOS Extras repo matches the one that's offered in Stream 8,
including being enabled by default.

config: Add Extras repo for CentOS Stream 9

---

mock-core-configs/mock-core-configs.spec

EL7 package is in a separate 'mock-2' branch.  The overall logic that
was in the %build section is thus useless now.

mock-core-configs: drop EL7 related hack

---

mock/py/mockbuild/package_manager.py

Like commit dcdaf718 if a source CA is copied to /usr/share/pki on the
host update-ca-trust inside the chroot will remove these from the trust.

mock: copy /usr/share/pki source CA certificates

---

mock-core-configs/etc/mock/alma+epel-8-ppc64le.cfg
mock-core-configs/etc/mock/almalinux-8-ppc64le.cfg

AlmaLinux now offers AlmaLinux 8 for POWER systems: https://almalinux.org/blog/almalinux-for-powerpc-85-stable-now-available/

Add AlmaLinux and Alma+EPEL 8 configs for POWER (ppc64le)

---

mock-core-configs/etc/mock/templates/centos-stream-9.tpl
mock-core-configs/mock-core-configs.spec

The key was regenerated to drop the SHA1 algorithm.
Requires: https://github.com/xsuchy/distribution-gpg-keys/pull/59
See: https://bugzilla.redhat.com/show_bug.cgi?id=2059424

config: Update CentOS Stream 9 Extras repo to use correct key

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl

allow n-2 gpg key for Fedora ELN

---

mock/mock.spec
mock/py/mock.py
mock/py/mockbuild/config.py
mock/py/mockbuild/constants.py
mock/py/mockbuild/uid.py

Two commits:
* one moves  setup_uid_manager() to mockbuild.uid module 
* second simplifies it
The motivation is that fedora-review calls load_config without uidManager param
https://pagure.io/FedoraReview/blob/master/f/src/FedoraReview/mock.py#_180
which fatally fails because recent changes require the uidManager there and it cannot be None.
When we merge this, I will prepare PR for fedora-review and we should synchronize release.

move setup_uid_manager to mockbuild.uid module 

---

.github/workflows/codeql-analysis.yml
.github/workflows/copr-builds.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

mock-core-configs/etc/mock/almalinux-8-x86_64.cfg

EPEL is not included in the baseline AlmaLinux configuration.

config: Fix description typo on AlmaLinux 8 for x86_64

---

mock-core-configs/etc/mock/circlelinux+epel-8-aarch64.cfg
mock-core-configs/etc/mock/circlelinux+epel-8-ppc64le.cfg
mock-core-configs/etc/mock/circlelinux+epel-8-x86_64.cfg
mock-core-configs/etc/mock/circlelinux-8-aarch64.cfg
mock-core-configs/etc/mock/circlelinux-8-ppc64le.cfg
mock-core-configs/etc/mock/circlelinux-8-x86_64.cfg
mock-core-configs/etc/mock/templates/circlelinux-8.tpl
mock-core-configs/mock-core-configs.spec

Circle Linux 8.6 released, now support x86_64, aarch64, ppc64le
archtecture.

configs: Add CircleLinux 8 configs

---

mock-core-configs/etc/mock/templates/opensuse-leap-15.4.tpl

One small bit leftover from Leap 15.3 -> 15.4 adaptation
Fixes: 0d4dca7afdd63a575bbd4ec76ac0712d498542d4

config: Fix dist value for openSUSE Leap 15.4

---

mock/README.md

It seems more useful to describe the most useful branches first.

README: reorder the branch description

---

docs/Feature-modularity.md

The new `module_setup_commands` was documented only in the release notes. Feature-modularity.md is a better place to document the option, especially while deprecating the obsolete option.

[CR-910] Update Fedora-modularity.md with new modularity commands

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl

Fedora ELN no longer provides an "Everything" repository. This update brings mock-core-configs in line with the content of the fedora-repos package.

Update Fedora ELN repo template

---

mock-core-configs/etc/mock/templates/epel-8.tpl
mock-core-configs/etc/mock/templates/epel-9.tpl

Namely use metalinks, as these tend to be more reliable:
https://pagure.io/fedora-infrastructure/issue/10767

config: sync epel-8 and epel-9 templates

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/config.py
mock/py/mockbuild/plugins/root_cache.py
mock/py/mockbuild/scm.py

On GNU/Linux distributions, tar is just synonym for GNU tar.  At least
we currently don't know of any distribution that would break this rull.
Relates: #925

Stop using the gtar symlink, use just tar

---

mock/py/mockbuild/podman.py

In nested podman containers, it's possible there are (harmless) warnings
printed by podman during the exec call [1]. These are getting caught by
Podman.get_container_id and tainting the container id generated. Add the
parameter returnStderr=False to the util.do call to mask these warnings
on stderr and stop them from tainting the container id.
[1]
...
Storing signatures
dfcd4643609a8042c3d7d53fd36110b7ce8b059b63cf984e1dc024be806f2686
Error: no container with name or ID "time=\"2022-08-08T09:40:15Z\"
level=warning msg=\"Ignoring global metacopy option, not supported with
booted kernel\"\ntime=\"2022-08-08T09:40:15Z\" level=warning
msg=\"Failed to add conmon to cgroupfs sandbox cgroup: error creating
cgroup path /libpod_parent/conmon: write
/sys/fs/cgroup/cgroup.subtree_control: device or …

podman.py: don't let podman warnings taint container id

---

mock-core-configs/etc/mock/templates/epel-8.tpl
mock-core-configs/etc/mock/templates/epel-9.tpl
mock-core-configs/etc/mock/templates/epel-next-8.tpl
mock-core-configs/etc/mock/templates/epel-next-9.tpl

The EPEL Next Koji repo inherits from the EPEL Koji repo.
The EPEL Koji repo has RHEL packages,
not CentOS Stream packages,
they give errors 403:
$ mock -r centos-stream+epel-next-9-x86_64 --remove libgcrypt
...
$ mock -r centos-stream+epel-next-9-x86_64 --enablerepo='local*' --install libgcrypt
[MIRROR] libgcrypt-1.10.0-4.el9_0.x86_64.rpm: Status code: 403 for https://infrastructure.fedoraproject.org/repo/rhel/rhel9/x86_64/rhel-9-for-x86_64-baseos-rpms/Packages/l/libgcrypt-1.10.0-4.el9_0.x86_64.rpm (IP: ...)

Do not expose the EPEL Koji repo when we are on EPEL Next

---

mock-core-configs/etc/mock/templates/almalinux-8.tpl
mock-core-configs/etc/mock/templates/almalinux-9.tpl

A new organization named `almalinuxorg` created since `almalinux` admin account is locked-down and not able to create new branches for publishing
Signed-off-by: Bala Raman <srbala@gmail.com>

Update to AlmaLinux Quay.io repo

---

mock-core-configs/mock-core-configs.spec

Therefore we need to enable the bootstrap image feature by default (same
as we already do for Fedora 31+).
Resolves: rhbz#2122171

EL7 yum can't even install the EL9 chroot

---

mock/mock.spec
mock/py/mockbuild/buildroot.py

We should only need the g+rw permissions so mock can write to those directories.  But we shouldn't need to re-chown everything to 'mock' chroot.  I tried to search through the history, and haven't found a real need for this.  According my testing, everything continues working.
Relates: #977

mock: stuff in /var/{lib,cache}/mock doesn't need SGID

---

mock/py/mock.py
mock/py/mockbuild/config.py
mock/py/mockbuild/exception.py
mock/py/mockbuild/uid.py
mock/tests/test_package_manager.py

This PR should eventually
- fix https://bugzilla.redhat.com/show_bug.cgi?id=2080735
- make the --list-configs much faster
- make the configuration easier to read
- make the configuration logic easier for security enhancement (see below)
I wish we could invent a new way of Mock configuration in the future, which doesn't require `exec()` call.  I'd suggest using `yaml` for this, and for the time being (one or two major releases) allow both variants).

minimize fork()ing during config loading

---

mock/py/mockbuild/exception.py

The exceptions are expected to have that attribute, see c6cfaa3be. Some of our code also relies on that attribute.
Complements: ca069b44ed5954c40fd504ce2adb95eabc9dd660

mock: re-introduce Error.msg attribute

---

.github/workflows/shell-diff-lint.yml

Differential ShellCheck is a GitHub action that performs **differential ShellCheck scans** on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get **reports only about newly added defects**. 
Since this repository has few shell scripts, I think you might find some value in having a shell linter. Differential ShellCheck action is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always …

ci(lint): add shell linter - Differential ShellCheck

---

mock/py/mock.py

In case we are on a RHEL-like distro, we will raise a self-explanatory RuntimeException anyway.
Complements: #998

mock: drop the redundant qemu-user-static warning

---

mock/py/mockbuild/buildroot.py

In order to be able to successfully build images properly inside of mock when device mapper is used (e.g. LVM), we need the device-mapper control device to exist.
However, we also need mock to gracefully ignore this if the host does not support DM/LVM and does not provide the device-mapper control device.

mockbuild/buildroot: Make DM control device available if supported

---

mock-core-configs/etc/mock/templates/openeuler-22.03.tpl

As newer 22.03 LTS SP1 released, switch to latest release.
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>

openEuler 22.03-SP1 released, so we switch to latest repo url

---

mock-core-configs/etc/mock/templates/almalinux-8.tpl
mock-core-configs/etc/mock/templates/almalinux-9.tpl

AlmaLinux's mirror management system uses GeoIP to try to serve the best mirrors possible and also has functionality to serve local mirrors within certain ASNs and subnets.  fastestmirror directly conflicts with this and completely breaks the latter 2 features.
More info: https://github.com/AlmaLinux/mirrors/tree/mirrors_service#how-it-works

disable fastestmirror on almalinux

---

mock-core-configs/etc/mock/fedora-38-aarch64.cfg
mock-core-configs/etc/mock/fedora-38-i386.cfg
mock-core-configs/etc/mock/fedora-38-ppc64le.cfg
mock-core-configs/etc/mock/fedora-38-s390x.cfg
mock-core-configs/etc/mock/fedora-38-x86_64.cfg
mock-core-configs/etc/mock/fedora-39-aarch64.cfg
mock-core-configs/etc/mock/fedora-39-i386.cfg
mock-core-configs/etc/mock/fedora-39-ppc64le.cfg
mock-core-configs/etc/mock/fedora-39-s390x.cfg
mock-core-configs/etc/mock/fedora-39-x86_64.cfg
mock-core-configs/etc/mock/templates/fedora-eln.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
mock-core-configs/mock-core-configs.spec

One week to branching according to https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html
* Branch Fedora Linux 38 from Rawhide -- Tue 2023-02-07
> WARNING: Make sure Fedora Copr maintainers are informed that
> WARNING: they should run 'copr-frontend branch-fedora 38'.
> WARNING: That has to be done right on time when branching is done.
@praiskup @FrostyX :eyes: :up: 
> WARNING: Please check that distribution-gpg-keys have the N+1 key,
It does.
>         you likely want to bump Requires: distribution-gpg-keys!
Done.

Branch Fedora 38

---

.github/workflows/python-diff-lint.yml

The new version is able to automatically upload SARIF data into the
GitHub UI.  Config updated according to the current vcs-diff-lint-action
documentation.

automation: update VCS Diff Lint config

---

mock-core-configs/etc/mock/templates/openeuler-22.03.tpl

Since openEuler 22.03 SP1 start using a new gpg key, mock config need to be updated.
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>

update openEuler gpg key

---

mock/py/mockbuild/package_manager.py

Distutils are not a part of standard library, and being moved to setuptools where copy_tree() isn't exposed.  Using shutils.copytree() seems more standard.
Resolves: rhbz#2165548

mock: don't use distutils copy_tree()

---

mock-core-configs/etc/mock/amazonlinux-2023-aarch64.cfg
mock-core-configs/etc/mock/amazonlinux-2023-x86_64.cfg
mock-core-configs/etc/mock/templates/amazonlinux-2023.tpl
mock-core-configs/mock-core-configs.spec

Now that Amazon Linux 2023 is GA, add mock config files for it.

Add Amazon Linux 2023 mock configs

---

mock/docs/mock.1

mock: manual page: fix the link to the upstream Mock documentation

---

mock/docs/site-defaults.cfg
mock/py/mock.py
mock/py/mockbuild/config.py

Previously, the "bootstrap_<option>" was copied into the "<option>" if and only
if the "<option>" was already defined (the value was replaced). Newly, we copy
all the options prefixed with bootstrap_ prefix, minus the 'bootstrap_image'
(the only one which has a specific semantics).

mock: fix bootstrap_* prefixed options

---

.tito/releasers.conf

Fedora 36 goes EOL on 2023-05-16, per:
https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html

releng: drop f36 from releasers

---

mock/py/mockbuild/config.py
mock/py/mockbuild/util.py

Pipes is a deprecated:
DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13

mock: use shlex instead of pipes

---

mock/py/mock.py

We need to first `commands.init()` before we access the buildroot.pkg_manager.
Found-by: #1082

Fix --dnf-cmd traceback

---

mock/py/mockbuild/package_manager.py

If possible, we'll use the target package manager for installing bootstrap.  But if not available on host, we'll try to use the most modern one preferably (the most likely available).

bootstrap: use DNF5 in package manager fallbacks

---

mock/py/mockbuild/plugins/bind_mount.py

Previously, the bind_mount plugin relied on pre-existing directory tree, typically created by the chroot directory tree by the _PackageManager installation.  So it was quite easy to mount stuff like `/var/run/socket` because `/var/run` always existed.  Problem happened with files like `/var/run/subdirectory/socket`.
Relates: #1091

bind_mount: pre-create dest directory before mounting file

---

mock-core-configs/mock-core-configs.spec

Use the %python3 macro for determining which Python interpreter to use. The interpreter selection of python3 on RHEL 8 is not guaranteed as the distro allows for any Python 3.x module stream to be used as an alternative for the `python3` symlink. However, only the `platform-python` (`python3` symlink provided by python36) has the DNF Python interfaces available to it.
On one of my RHEL 8 systems where I have Python 3.11 configured as the global `python3`, the following output was logged when upgrading:
```text
Upgrading        : mock-core-configs-38.5-1.el8.noarch         2/8 
Running scriptlet: mock-core-configs-38.5-1.el8.noarch         2/8 
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dnf'
Warning: file …
```

Use python3 macro for post scriptlet

---

mock/py/mockbuild/file_util.py
mock/py/mockbuild/package_manager.py

The problem with default shutil.copytree() is that it doesn't "update" existing directories.  So I was wrong in adf58f0c172dd8, we can't pre-create the dest-directory.  More, the certificate directory is being updated over and over with subsequent calls, and we want to keep updating the dest directory.  For this to work correctly, we need to use 'shutil.copytree(dirs_exist_ok=True)' which is though not in Python 3.6.
Therefore we try the 'shutil.copytree' first (works for Python standard library 3.7+), and we fallback to the deprecated 'distutils' copy_tree() method to stay compatible with Python 3.6.
Partly-reverts: adf58f0c172dd8d5493ca5e8dead5ade23caf711
Fixes: #1094

Fix certificate copying

---

mock/py/mockbuild/package_manager.py

Seems like there's not yet the time, per: https://github.com/rpm-software-management/dnf5/issues/617
Reverts: 6c7cb9fcb248ef6ba7ab0559eefc02c4065e77f2.
Relates: #1089

mock: don't use dnf5 for bootstrap installation, yet

---

mock/pylintrc

Pylint tool is now used in the upstream vcs-diff-lint CI, and it is able to filter-out the old issues (differential analysis).  So re-enabling even all the low-prio warnings (we used to have to silence the full-scan output) shouldn't really cause annoyance.

pylintrc: disable import-error, but re-enable other checks

---

mock/docs/site-defaults.cfg
mock/py/mock.py
mock/py/mockbuild/config.py

This is sometimes problematic for test-suite leftovers, and --scrub. For example all GNU utilities depending on gnulib's getcwd module do some tests related directory structure limits:
https://git.savannah.gnu.org/cgit/gnulib.git/tree/m4/getcwd-path-max.m4?id=c39d83dd0e487e7861349de9fdca7443358fc5f7#n104

mock: increase the recursion limit from 1000 to 5000

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py

Not the 'dnf-plugins-core' (which transitively brings the python3-* package) that only contains manual pages.

bootstrap: install just python3-dnf-plugins-core

---

mock/py/mock.py

This might cause troubles in chroots that don't use '$releasever' properly, or have weird 'if target_arch' Jinja hacks (for example different set of repositories for different architectures).
Possible fixes/workarounds that might be interesting to user:
- Using 'config_opts["bootstrap_target_arch"] = "ppc64le"', so the `target_arch` affects how the `dnf.conf` in bootstrap is generated.
- Using 'config_opts["bootstrap_forcearch"] = True'.  This will revert the effect of this patch for particular config.
Fixes: #1110

"native" bootstrap, not cross-arch

---

mock/py/mock.py
mock/py/mockbuild/util.py

When a RHEL container is started, the entitlement files are made available in-container and users can then 'dnf install' stuff inside. The entitlement directory though isn't /etc/pki/entitlement, but /etc/pki/entitlement-host.
Mock configuration currently expects that the files exist in /etc/pki/entitlement, so let's try to simplify the job to the end user, and copy the keys into the that directory.  Alternatively (is it needed?) we could create yet another entitlement directory specific to Mock, and change the PEM paths in mock-core-configs.

Automatically handle Red Hat subscription in-container

---

.packit.yaml

Use monorepo syntax for Packit builds which should simplify the config.
More info:
* https://packit.dev/docs/configuration/#packages
* https://packit.dev/posts/monorepos/

Use monorepo syntax for Packit builds

---

mock-core-configs/mock-core-configs.spec
mock/mock.spec

The 'postX' Version tag allows us to explicitly require a specific pre-release version of mock in a pre-release mock-core-configs Version. The tag can be bumped during the development according to the actual needs.
This way of version handling is also a way-around the missing Tito RFE: https://github.com/rpm-software-management/tito/issues/460

Post-release administrivia

---

mock/py/mockbuild/mounts.py
mock/py/mockbuild/package_manager.py

Typically, when user pressed Ctrl+C during the long-running 'dnf install' command, KeyboardInterrupt was raised and unhandled, causing that the buildroot mounted in bootstrap stayed mounted (eventually breaking even subsequent `mock --scrub=all`).
While on it, stop using manual "mount_bootstrap" and use only the context manager.

mock: umount essential/bootstrap mountpoins on exception

---

mock/py/mockbuild/file_util.py

When you Ctrl+C a child can still write something in directory, so try again. Previously this lead to traceback as we handled only this situation when the data were excluded.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2186613

during cleanup when leftover is in directory, try again

---

mock/py/mockbuild/config.py

Then, in real life configuration files we can assume it already is a dictionary and we can just:
config_opts["dnf5_avoid_opts]["remove"] = ["--allowerasing"]
Instead of:
config_opts["dnf5_avoid_opts] = {
"remove": ["--allowerasing"],
}

Provide <pkg_manager>_avoid_opts defaults as empty dict

---

mock/py/mockbuild/config.py

This fixes 'mock --chain' with package_manager=dnf5, because the util.py code tries to append repositories into 'dnf5.conf':
Traceback (most recent call last):
File "/usr/libexec/mock/mock", line 1087, in <module>
exitStatus = main()
File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
result = func(*args, **kw)
File "/usr/libexec/mock/mock", line 847, in main
result = run_command(options, args, config_opts, commands, buildroot, state)
File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
result = func(*args, **kw)
File "/usr/libexec/mock/mock", line 888, in run_command
result = commands.chain(args, options, buildroot)
File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
result = …

Make config_opts['dnf5.conf'] alias to config_opts['dnf.conf']

---

mock/py/mockbuild/config.py

Since https://github.com/rpm-software-management/dnf5/issues/461 is fixed, we can drop the very same work-around for 'builddep'.
Relates: #1149

For now don't use --allowerasing with 'dnf5 remove'

---

docs/Feature-container-for-bootstrap.md
mock-core-configs/etc/mock/templates/mageia-7.tpl
mock-core-configs/etc/mock/templates/mageia-branched.tpl
mock-core-configs/etc/mock/templates/mageia-cauldron.tpl
mock/docs/site-defaults.cfg
mock/mock.spec
mock/py/mockbuild/config.py
mock/py/mockbuild/package_manager.py

This feature exists for long time. I think it is time to enable it by default. It will allows us to run Mock without package manager on host.

enable use_bootstrap_image by default

---

mock/py/mockbuild/buildroot.py

Without the FUSE device, we cannot use FUSE filesystems with image builds.
This is particularly important for RPM-OSTree builds that use FUSE as part of the image build process.
Reference: https://pagure.io/fedora-infrastructure/issue/11420

mockbuild/buildroot: Make the FUSE device available if supported

---

mock/py/mockbuild/backend.py

Turns out that the very next command 'self.buildroot.delete()' already does this properly (locking the buildroot first to assure no other mock process is killed, and then calling killOrphans).
Also, the '--rebuild' action calls 'do_rebuild' with 'commands.clean()' first - which without asking killed existing background Mock processes:
$ mock /tmp/tito/mock-4.1.post1-1.git.3565.2f68fb1.fc38.src.rpm
INFO: mock.py version 4.1.post1 starting (python version = 3.11.4, NVR = mock-4.1.post1-1.git.3565.2f68fb1.fc38)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: Start(/tmp/tito/mock-4.1.post1-1.git.3565.2f68fb1.fc38.src.rpm)  Config(fedora-38-x86_64) …

Don't kill orphans without the exclusive lock

---

docs/Release-Notes-Next.md
mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py

The `allow_vendor_change=no` option is going to be set in DNF5 as default: https://github.com/rpm-software-management/dnf5/issues/712
With Mock though, it is very common to override the distro default package with a custom one (newer or fixed one?).  And blindly trying to keep the Vendor tag unchanged for the overridden packages would be very complicated, without any real benefits.
Note `allow_vendor_change=no` only affects the cases when some package in the buildroot/bootstrap needs to be _updated_ while _typically_ all the packages are only _installed_ at the beginning and are already up2date.  This is therefore mainly related to the --chain option, or cases like `bootstrap_image_ready=False`, `update_before_build`, etc.
Fixes: #1155

Use 'allow_vendor_change=yes' with DNF5

---

mock/py/mockbuild/util.py

With all the --uniqueexst, --rootdir, --resultdir, etc. options it is easy to make a mistake, so this info helps to reassure us everything is OK.

Logging what chroot we are killing the orphans in

---

mock/py/mockbuild/podman.py

The util.do(printOutput=True) prints commands out into Mock's stdout, instead of just "logging-out" (which goes to stderr).  This was breaking the 'mock --shell' feature stdout which is typically parsed by scripts.

Don't break --shell stdout with Podman class

---

mock/py/mockbuild/buildroot.py
mock/py/mockbuild/package_manager.py
mock/tests/test_package_manager.py

We can not use user_mountpoints because these aren't (historically, not
sure what are the reasons) mounted too late during the Buildroot
preparation (after the self._init_pkg_management()).  This isn't
actually an issue when 'use_bootstrap_image == False' because we use the
package manager on host (so it actually sees the repository on host).
So newly we place the local_repo mount points into the "managed"
category, which seems even semantically better now.  We though need to
call the 'self.mounts.mountall_managed()' method a little bit later than
before, when the local repo BindMountPoints are already defined by
self.pkg_manager.initialize().
This problem has been triggered by the LVM test-case that creates a
custom local_repo (on host) with `baseurl=/tmp/foo` that needs to be …

bootstrap_image and the local repositories

---

mock/py/mock.py
mock/py/mockbuild/config.py
mock/py/mockbuild/package_manager.py

When building an i?86 package (with i?86 chroot config) on an x86_64 host, we report to kernel that we work in 32 bit mode (using the '/bin/setarch'-like condPersonality() call).  This is completely OK and desired for the build (target) chroot, but not for the bootstrap chroot which is generated from a container image.
The container image has always a host-native arch (unless there's a configuration error).  So the pre-installed packages are x86_64. When we want to install additional packages there (typically to provide the 'dnf builddep' command in bootstrap), and we do that using the package manager already installed in bootstrap image (no package manager on host is required!), the package manager is confused by the 32-bit mode and resolves '$basearch' into 'i386' instead of 'x86_64'. …

Fix multilib builds with --use-bootstrap-image

---

mock/mock.spec

Hi, as you are probably aware, the switch to DNF 5 has been postponed, likely to Fedora 41. In Fedora 39, the `dnf` command will be provided by the `dnf` package, and DNF 5 will not be installed by default.
Here, I suppose the `Suggests` is not too important, but whether the spec file suggests DNF 4 or DNF 5 in some version of Fedora might as well match the default package manager in that version.
In the meantime, we have set up a testing [COPR repository](https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-testing/) that provides a version of DNF 5 that obsoletes DNF 4. It can be used to test software in an environment similar to the future release of Fedora (whichever that will be) when DNF 5 replaces DNF 4:
```
sudo dnf-3 copr enable rpmsoftwaremanagement/dnf5-testing …
```

Suggest dnf5 in Fedora 41+, not Fedora 38+

---

mock/py/mockbuild/exception.py
mock/py/mockbuild/podman.py

Defining a new BootstrapError() exception covering the bootstrap chroot preparation problems.
Make sure that stderr output is dumped into logs when some failure happens.
When `podman pull` fails, we just throw a logger.error() message now, and delay the fatal failure till the `podman image mount` attempt. Users might have the image pre-downloaded.

podman: better "podman pull / image mount" error reporting

---

mock/docs/site-defaults.cfg
mock/mock.spec
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/config.py
mock/py/mockbuild/podman.py
tox.ini

Needs to be applied on top of #1199, if at all.

podman: experiment with "fallback to normal bootstrap"

---

mock/py/mock.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/util.py

This complements 79c36e81be4535b8e45bd33ac95a5b98b2951e37 with useful info, Mock already falls-back to using "normal bootstrap" if in Docker without --privileged.
Fixes: #1184

podman: warn that 'docker run --privileged' may be needed

---

docs/Plugin-Scm.md
mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py
mock/py/mockbuild/scm.py

This allows users to use repositories with non-standard structures.
There is already a 'spec' scm option to specify a SPEC file in arbitrary directories. Why not allow arbitrary source directories to be specified as well?

Add int_src_dir option to specify source directory

---

mock/mock.spec
releng/release-notes-next/package-managers-recommended.feature

Actually, having DNF5 on Fedora 38 Mock **host** is still a good idea for the future when we'll be building Fedora 41 chroots.
This reverts commit 8cca2d02aef81c8dbfb05ba46bb2e8bdf37baafb.

Suggests DNF5 installation on 38+ again

---

mock/py/mock.py
mock/py/mockbuild/mounts.py
releng/release-notes-next/hiding-mounts-permissions.bugfix

We don't need to allow anyone writing there, these mountpoints are just hiding the complicated recursive bind-mounts in Mock's separate namespace.

mounts: make the hide-from-host mountpoints root-only

---

mock/py/mockbuild/backend.py
releng/release-notes-next/rpm-ds.bugfix

Use `rpm.ds(hdr)` instead of now removed hdr.dsFromHeader()

---

mock/py/mockbuild/podman.py
releng/release-notes-next/podman-image-unmount.bugfix

This is to fix the 27-nspawn.tst which again detects an unwanted stdout output from Mock.
Follow-up-for: b626045d2bdde026e0278dd1971ed54b217cc7af

podman: redirect 'podman pull' stdout to stderr

---

mock/README.md

- we are already on v5.x -> and the versioning goes up quite quickly so let's make the `main` statement a bit more generic
- There are other Copr instances already, use `Fedora Copr`
- Mention how to install pre-release Mock from Copr

README.md: cleaning up

---

mock/py/mockbuild/podman.py
releng/release-notes-next/epel-8-compat.bugfix.md

Per report in Bodhi update:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-45ace77fca

capture_output=True is not supported on EL8

---

mock-core-configs/mock-core-configs.spec

Properly handle Fedora ELN in `mock-core-configs/mock-core-configs.spec` by setting the default to `fedora-eln-x86_64.cfg` instead of `fedora+epel-rawhide-x86_64.cfg` which doesn't exists.

Properly handle Fedora ELN

---

mock-core-configs/etc/mock/templates/opensuse-leap-15.5.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/leap15.5-gpgkeys.config

The openSUSE Backports signing key was replaced in May for Leap 15.5, so this configuration needs to be updated for the new key.
Requires: https://github.com/xsuchy/distribution-gpg-keys/pull/108
Fixes: #1240

config: Use the correct openSUSE Backports key for Leap 15.5

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl
releng/release-notes-next/fedora-eln-image.config

Relates: https://github.com/fedora-eln/eln/issues/164
Fixes: https://github.com/rpm-software-management/mock/issues/1238

Fix the Fedora ELN bootstrap image

---

mock/py/mockbuild/backend.py
releng/release-notes-next/generate_buildrequires.bug

When the %generate_buildrequires section behaved unpredictable, it was possible to successfully build a package with unsatisfied BuildRequires. Now, the build will fail.
Fixes https://github.com/rpm-software-management/mock/issues/1246

Dynamic BuildRequires: Prevent generation of unsatisfied dependency

---

mock/py/mockbuild/backend.py
releng/release-notes-next/generate_buildrequires_prep.feature

This is built on top of https://github.com/rpm-software-management/mock/pull/1249
Hence opening it as a draft until that one is finalized.

Only %prep once when running %generate_buildrequires multiple times

---

mock-core-configs/etc/mock/templates/openmandriva-cooker.tpl
mock-core-configs/etc/mock/templates/openmandriva-rolling.tpl
releng/release-notes-next/mandriva-dnf-python.config

configs: mandriva provides python-* not python3-* packages

---

.github/workflows/fedora-tox.yml

Per discussion in:
https://github.com/fedora-infra/mock/pull/3

workflows: enable tox tests in all branches

---

mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
releng/release-notes-next/dnf5-for-f40.config

Per Fedora system wide change proposal:
https://fedoraproject.org/wiki/Changes/BuildWithDNF5
https://pagure.io/fesco/issue/3096
Fixes: #1147

Fedora 40+ to use DNF5 for building

---

mock-core-configs/README.md
mock-core-configs/mock-core-configs.spec

See also #1171
We have a lot of chroots, so it is not uncommon, that some of them break from time to time. Most of the reports that I've got were about Fedora ELN but there were others as well. People usually report them as a Copr issue, so I need to point them here (and make sure the maintainer knows) or point them to the distribution issue tracker, which I don't remember from the top of my head.
Hopefully, this will improve the situation.
What do you think?

Mock core configs - README.md with maintainers and issue trackers

---

mock/docs/site-defaults.cfg
mock/mock.spec
mock/py/mockbuild/config.py
mock/py/mockbuild/plugins/rpmautospec.py
mock/requirements.txt
mock/tests/conftest.py
mock/tests/plugins/test_rpmautospec.py
releng/release-notes-next/rpmautospec-plugin.feature
tox.ini

This plugin preprocesses spec files using %autorelease and/or %autochangelog in the mock chroot prior to building SRPMs. The `rpmautospec` package will be installed into the chroot if necessary.
/cc @sgallagher

Add rpmautospec plugin

---

mock/py/mockbuild/package_manager.py
releng/release-notes-next/dnf5-logs-with-no-pty.bugfix

If DNF 5 sees an "interactive" TTY on stdout, it will try to draw progress bars and cause the Mock logs to be garbled: https://github.com/fedora-copr/copr/issues/3040. A simple fix is to have DNF 5 output to a pipe instead of a PTY.
I'm not sure why output is collected via a PTY from yum/dnf (seems to start from commit 99ca2fa), but it's probably no longer needed for DNF 5?

dnf5: Don't output to a PTY

---

mock/py/mockbuild/plugins/rpmautospec.py
mock/tests/plugins/test_rpmautospec.py
releng/release-notes-next/rpmautospec-plugin-fix-install-deps.bugfix

That’s what I get for only relying on unit tests 😉.
Thanks to @azhuzhu for debugging and working out the patch!

Fix installing rpmautospec plugin dependencies

---

mock-core-configs/etc/mock/templates/fedora-branched.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl

With DNF5, the cache directory for root is now configured via `system_cachedir`.  Dnf4 seems to silently ignore this config option.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2256945
Relates: https://github.com/rpm-software-management/dnf5/issues/1150

dnf5: configure system_cachedir for dnf5

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py
mock/py/mockbuild/shadow_utils.py
releng/release-notes-next/use_host_shadow_utils.config

This is the suggestion that @sgallagher offered; I tested this on a FreeIPA-enrolled system and it worked.
I'm a bit nervous about the comment above the line about old shadow-utils being problematic; but we definitely also have the case where shadow-utils config from the host "leaks" into the chroot. I'm not sure which problem is bigger.

Run shadow-utils inside the chroot to avoid contradictory configurations

---

mock/mock.spec

This was the only loosely specified dependency that could lead to incompatible installations. These specific requirements become crucial when attempting to install Mock from the Git main branch or even from a pull request Copr repository. In such cases, it often involves a 'mock' downgrade, and it's advisable to downgrade all the sub-packages in a single transaction.

rpm: mock requires a precise version of mock-filesystem

---

mock/py/mockbuild/buildroot.py
mock/py/mockbuild/uid.py

Group ownership and process ownership defaults to `mock`

---

mock/py/mockbuild/package_manager.py
mock/tests/test_package_manager.py

This fixes parsing of dnf.conf containing url-encoded links.
Fixes: #1310

package_manager: disable %-interpolation in dnf.conf parser

---

mock-core-configs/etc/mock/templates/mageia-branched.tpl
mock-core-configs/etc/mock/templates/mageia-cauldron.tpl
mock/docs/site-defaults.cfg
mock/py/mock.py
mock/py/mockbuild/config.py
mock/py/mockbuild/package_manager.py
mock/tests/test_config_templates.py
releng/release-notes-next/repo-arch.feature

This fixes the native bootstrap preparation for cross-arch (emulated) builds.

New {{ repo_arch }} variable usable instead of $basearch

---

mock/py/mockbuild/config.py
mock/tests/data/config-001/fedora-rawhide-x86_64.cfg
mock/tests/data/config-001/site-defaults.cfg
mock/tests/data/config-001/templates/fedora-rawhide.tpl
mock/tests/data/home-001/.config/mock.cfg
mock/tests/data/home-001/.config/mock/fedora-rawhide-x86_64.cfg
mock/tests/test_config_loader.py
releng/release-notes-next/root_cache_invalidation.bugfix

The root_cache plugin assures that no new configuration file in the `config_opts['config_paths']` list is newer than the root_cache cache tarball, otherwise the caches are invalidated.
The bug is caused by use of improper set operation (union() doesn't modify the calling object).

Fix root_cache invalidation triggered by config changes

---

mock-core-configs/mock-core-configs.spec
releng/release-notes-next/init-and-ownership-problems.bugfix
releng/release-notes-next/mageia-7-eol.config
releng/release-notes-next/mageia-cross-arch.config
releng/release-notes-next/mock-filesystem-deps.bugfix
releng/release-notes-next/openmandriva-i686-eol.config
releng/release-notes-next/percent-interpolation-in-dnf-config.bugfix
releng/release-notes-next/report-file-system-type.feature
releng/release-notes-next/use_host_shadow_utils.config

New PRs will "enforce" adding the release notes snippets, but we forgot to add some in this release cycle.
The mock-core-cconfig -> mock requirement bump is needed for the new '{{ repo_arch }}' jinja2 template support.

Release Notes before #1308, and requirement bump

---

docs/Plugin-ChrootScan.md
mock/py/mockbuild/plugins/chroot_scan.py
releng/release-notes-next/chroot_scan_tarball.feature

I just tried to comment-out the 'tarball' option, and Mock started to fail with KeyError traceback.  It's better to use config_opts.get().
While on it, fix documentation to suggest configuration that is not prone to this kind of errors (the default values stay defined).

ChrootScan: don't fail for missing option

---

mock-core-configs/etc/mock/templates/fedora-branched.tpl
releng/release-notes-next/f40-dnf5.config

Fixes https://bugzilla.redhat.com/2264535

Use dnf5 on Fedora 40+

---

mock/py/mockbuild/backend.py
releng/release-notes-next/rhbz-2254328.bugfix

Avoid Traceback for resultdir ENOSPC

---

mock/etc/bash_completion.d/mock
mock/mock.spec
mock/precompile-bash-completion
releng/release-notes-next/faster-bash-completion.feature

bash-completion: pre-build the list of mock known options

---

mock/py/mockbuild/config.py
releng/release-notes-next/allowerasing.bugfix

DNF subcommands such as `repoquery`, `makecache` , `search`, and `info`, doesn't support the `--allowerasing` parameter.

Don't use --allowerasing for more DNF commands

---

docs/configuration.md

I am using Fedora. I was looking for a way of using an user's own `default.cfg` instead of the `/etc/mock/default.cfg`. Because I wanted to use the Fedora rawhide as default instead of the current default to the latest Fedora stable version 39. 
```
$ ls /etc/mock/default.cfg -l
lrwxrwxrwx. 1 root root 20 Feb 26 14:57 /etc/mock/default.cfg -> fedora-39-x86_64.cfg
```
I didn't want to modify the `/etc/mock/default.cfg`. Because it might prevent the future update of the file by upgrading the `mock-core-configs` RPM package.
I was not able to find the user's `default.cfg` in the current documents. Below is a part of explaining the `default.cfg`. But it doesn't explain about the user's `default.config` explicitly.
https://github.com/rpm-software-management/mock/blob/fc1f7d4d22777d17f41aa6482e6 …

docs: add the case of user's default.cfg.

---

mock/py/mockbuild/file_downloader.py
releng/release-notes-next/FileDownloader-original_name.bugfix

In some cases, such as fail of "mock --chain --recurse some.src.rpm.tofail", FileDownloader "cls" may not have a "backmap" attribute. So we have to check if it exists before accessing it.
Fixes: #1345

Rewrites "original_name" method to check if "cls" has a "backmap"

---

mock/etc/bash_completion.d/mock
releng/release-notes-next/buildlog-parser-completion.bugfix

I have a feeling that no one is using mock-parse-buildlog, but we are installing `%{_datadir}/bash-completion/completions/mock-parse-buildlog`, which does nothing right now.

bash-completion: add mock-parse-buildlog

---

mock-core-configs/etc/mock/mageia-10-i586.cfg
mock-core-configs/etc/mock/mageia-10-i686.cfg
mock-core-configs/etc/mock/mageia-cauldron-i686.cfg
releng/release-notes-next/cauldron-i686.config

Mageia replaced i586 arch with i686 in Cauldron, and thus also for upcoming Mageia 10.

config: Replace Mageia 10 and Cauldron i586 configs with i686

---

mock/py/mockbuild/buildroot.py
releng/release-notes-next/no-tmpdir-for-no-nosync.bugfix

Do not create temporary Buildroot.tmpdir for disabled nosync

---

mock/py/mockbuild/buildroot.py
releng/release-notes-next/chown-homedir.bugfix

Not setting the ownership caused problem when doing
mock -r fedora-rawhide-x86_64 --chroot --unpriv "touch ~/test"
lets make sure that homedir is always writable but keep the recursion only in rebuild as was previously.
Fixes: #1364

always set ownership of homedir (but not recursively)

---

mock-core-configs/etc/mock/circlelinux+epel-9-aarch64.cfg
mock-core-configs/etc/mock/circlelinux+epel-9-ppc64le.cfg
mock-core-configs/etc/mock/circlelinux+epel-9-s390x.cfg
mock-core-configs/etc/mock/circlelinux+epel-9-x86_64.cfg
mock-core-configs/etc/mock/circlelinux-9-aarch64.cfg
mock-core-configs/etc/mock/circlelinux-9-ppc64le.cfg
mock-core-configs/etc/mock/circlelinux-9-s390x.cfg
mock-core-configs/etc/mock/circlelinux-9-x86_64.cfg
mock-core-configs/etc/mock/templates/circlelinux-9.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/add-circlelinux-9-mock-config.config

Circle Linux 9.3 released, now support x86_64 aarch64 ppc64le s390x.

Add Circle Linux 9 configs

---

mock/py/mockbuild/scm.py
releng/release-notes-next/scm-git_timestamps.bugfix

I am getting the following type error when attempting to use SCM with Git timestamps on RHEL 9 and Fedora.  Can something like this be applied to fix it?
```
...
File "/usr/lib/python3.9/site-packages/mockbuild/scm.py", line 118, in adjust_git_timestamps
for f in proc.communicate()[0].split('\0')[:-1]:
TypeError: a bytes-like object is required, not 'str'
```

scm: Use bytes for compatibility with subprocess stdout

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl
releng/release-notes-next/eln-uses-dnf5.config

Relates: https://pagure.io/releng/issue/11895

configs: BuildWithDNF5 for ELN

---

docs/Release-Notes-5.6.md

See PR #1369
I accidentally listed the contributors since `mock-4.1-1..HEAD`, not since the actual previous version.

Fix the contributor list for the latest release

---

mock-core-configs/etc/mock/templates/centos-stream-10.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/c10s-compose.config

Fixes https://github.com/rpm-software-management/mock/issues/1372
Depends on: https://github.com/xsuchy/distribution-gpg-keys/pull/119

Add composed c10s repos

---

mock-core-configs/etc/mock/templates/fedora-branched.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
releng/release-notes-next/rawhide-bootstrap-image-ready.config

The latest Rawhide images already have dnf5-plugins package:
https://pagure.io/fedora-kiwi-descriptions/pull-request/63

configs: Fedora 41+ configuration images are "dnf5 ready"

---

docs/Plugin-CCache.md
mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py
mock/py/mockbuild/plugins/ccache.py
releng/release-notes-next/hashdir.feature

Setting it to false allows ccache to be shared across different package NEVRs, but the debuginfo files may contain incorrect information in exchange:
https://ccache.dev/manual/4.10.html#config_hash_dir
Fixes #1395

Add hashdir option to ccache plugin

---

mock/integration-tests/22-rootdir.tst
mock/integration-tests/runtests.sh

Mock has a build-in abstraction for in-bootstrap DNF version (or YUM), there's no need to check if DNF exists on host (this whole dropped test code comes from the pre-bootstrap era).

Fix the Testing Farm testsuite

---

mock-core-configs/etc/mock/eol/templates/centos-7.tpl
releng/release-notes-next/centos-7-eol.config

Switch CentOS 7 repository configuration from `mirrorlist.centos.org` to `vault.centos.org`, because otherwise mock builds against CentOS 7 (or EPEL 7) don't succeed anymore for me.

configs: Switch CentOS 7 to vault.centos.org

---

mock-core-configs/etc/mock/fedora-eln-i386.cfg
releng/release-notes-next/fedora-eln-i386.config

ELN has dropped ix86 multilib builds: https://pagure.io/releng/issue/12171

configs: drop fedora-eln-i386

---

mock-core-configs/etc/mock/centos-stream+epel-10-aarch64.cfg
mock-core-configs/etc/mock/centos-stream+epel-10-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-10-s390x.cfg
mock-core-configs/etc/mock/centos-stream+epel-10-x86_64.cfg
mock-core-configs/etc/mock/templates/epel-10.tpl
releng/release-notes-next/c10s+epel.config

These work with Koji EPEL buildroot only for now since there are no composes, yet.
Fixes: #1421

Add CentOS Stream 10 + EPEL 10 configs

---

.tito/packages/mock-core-configs
docs/Release-Notes-Configs-41.1.md
docs/index.md
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/add-openeuler-2403.config
releng/release-notes-next/c10s+epel.config
releng/release-notes-next/c10s-metalink.config
releng/release-notes-next/centos-7-eol.config
releng/release-notes-next/fedora-41-branching.feature
releng/release-notes-next/fedora-eln-i386.config
releng/release-notes-next/fedora-rawhide-key-plus-one.config
releng/release-notes-next/rawhide-bootstrap-image-ready.config

/usr/bin/tito tag --use-version=41.1
./releng/generate-release-notes --config-only --use-version 41.1

Release mock-core-configs v41.1

---

mock-core-configs/etc/mock/eol/centos+epel-7-aarch64.cfg
mock-core-configs/etc/mock/eol/centos+epel-7-ppc64.cfg
mock-core-configs/etc/mock/eol/centos+epel-7-ppc64le.cfg
mock-core-configs/etc/mock/eol/centos+epel-7-x86_64.cfg
mock-core-configs/etc/mock/eol/centos-7-aarch64.cfg
mock-core-configs/etc/mock/eol/centos-7-ppc64.cfg
mock-core-configs/etc/mock/eol/centos-7-ppc64le.cfg
mock-core-configs/etc/mock/eol/centos-7-x86_64.cfg
mock-core-configs/etc/mock/eol/oraclelinux+epel-7-aarch64.cfg
mock-core-configs/etc/mock/eol/oraclelinux+epel-7-x86_64.cfg

Disclosure: This is my first PR on a public project. Apologies if I missed to follow any rules on this repo (I did not see a  contribution guide)
I think there was a typo introduced when CentOS7 and EPEL7 templates were EOL´d with #1397 
Please disregard if I misunderstood template locations and corresponding includes.
Did not file an issue yet since I do not have access to a recent mock version that has #1397 changes.
Have a nice day :)

Fix EOL template locations for CentOS7/EPEL7

---

mock/docs/site-defaults.cfg
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/config.py
releng/release-notes-next/bootstrap-skip-image-pull.feature

Relates: #1393
I'm trying to split the PR into smaller pieces.

Skip the "podman pull" for bootstrap when not needed

---

.github/workflows/towncrier.yml

The since_last_remote_commit doesn't seem to work correctly;  for some reason, it sometimes gives us a limited set of changed files (appears like it was generated since the last commit in the very same PR, not from the target branch), example:
https://github.com/rpm-software-management/mock/actions/runs/10616932275/job/29431772686?pr=1393

towncrier: update to v45 && use defaults

---

.github/workflows/python-diff-lint.yml

ci: update vcs-diff-lint config
- sync with Copr: https://github.com/fedora-copr/copr/blob/main/.github/workflows/python-diff-lint.yml
- enable debugging
- lint also behave/ and releng/ files

ci: update vcs-diff-lint config

---

.github/workflows/python-diff-lint.yml
pylintrc

This requires a top-level pylintrc file.  The previous per-subdir
solution was broken (each subdir would need to provide a specfile, or
the .vcs-diff-lint.yml file to work correctly).

CI: lint the whole project

---

docs/Plugin-CCache.md
mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py
mock/py/mockbuild/plugins/ccache.py
releng/release-notes-next/ccache_debug.feature

Setting it to `True` creates per-object debug files that are helpful when debugging unexpected cache misses.
https://ccache.dev/manual/4.10.html#config_debug

Add `debug` option to the ccache plugin

---

docs/Plugin-CCache.md
mock/docs/site-defaults.cfg
mock/py/mockbuild/config.py
mock/py/mockbuild/plugins/ccache.py
releng/release-notes-next/ccache-show-stats.feature

Zero the ccache stats at the beginning of the build and then display the ccache stats at the end of the build to see how effective ccache was.

Show ccache stats at the end of the build

---

mock-core-configs/etc/mock/centos-stream+epel-8-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-9-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-8-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream+epel-next-9-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream-8-ppc64le.cfg
mock-core-configs/etc/mock/centos-stream-9-ppc64le.cfg
mock-core-configs/etc/mock/rhel-7-ppc64le.cfg
mock-core-configs/etc/mock/rhel-8-ppc64le.cfg
mock-core-configs/etc/mock/rhel-9-ppc64le.cfg
releng/release-notes-next/ppc64le-not-powerpc64le-host-cpu.config

This is what Koji does for all architectures.  The macro is used by
rpmbuild while matching 'ExclusiveArch' patterns.  E.g. "%java_arches"
then contains 'ppc64le', but by default '_host_cpu' contains powerpc64le
on Fedora.
RPM checks %_target_cpu with %_build_cpu fallback:
https://github.com/rpm-software-management/rpm/blob/21457de886faf2415500a8bb7cc6c816d72939ef/build/parsePreamble.c#L442-L449
For 'BuildArch: noarch' packages, %_target_cpu is 'noarch', fallback is
used and '%_build_cpu' is defined as '%_host_cpu' in redhat-rpm-config.
This is set by 'config.guess' to powerpc64le.
TODO: submit a redhat-rpm-config issue
TODO: resolve other EPEL/Fedora targets
Relates: https://github.com/fedora-copr/copr/issues/2870
Relates: https://bugzilla.redhat.com/show_bug.cgi?id=1461288

override ppc64le %_host_cpu

---

mock-core-configs/etc/mock/templates/centos-stream-10.tpl
releng/release-notes-next/c10s-bootstrap-ready.config.md

Since CentOS Stream 10 hasn't been released yet, the container image exists but is using the tag stream10-development instead of stream10. At some point (probably the release announcement) it will start using the stream10 tag.  This image is "ready" (i.e. `dnf builddep` is pre-installed).
cc: @tdawson

Enable bootstrap container for CentOS Stream 10

---

.packit.yaml
mock/docs/site-defaults.cfg
mock/integration-tests/setup-playbook/tasks/main.yml
mock/mock.spec
mock/py/mockbuild/config.py
mock/py/mockbuild/package_manager.py
releng/release-notes-next/dnf4-config-is-alias-to-dnf.feature

Fixes: https://github.com/rpm-software-management/mock/issues/1271

Make 'package_manager = dnf4' equivalent to 'package_manager = dnf'

---

mock/py/mockbuild/backend.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/plugins/rpkg_preprocessor.py
mock/py/mockbuild/plugins/rpmautospec.py
mock/tests/plugins/test_rpmautospec.py
releng/release-notes-next/nspawn-args-chroot-bootstrap.bugfix

Which also includes all doOutChroot(), because that method calls doChroot() internally.
This issue was found when trying to workaround an issue [1] when SELinux policy forbid systemd-machine to create a varlink socket and thus start. This resulted in systemd-nspawn not being able to register a machine. To workaround this, Tomáš added the following snippet to the configuration:
config_opts['nspawn_args'] = ['--register=no']
So that systemd-nspawn does not try to register the machine with systemd-machine.  However, this had no effect (and the argument was not visible on command-line and still failed).
[1] https://issues.redhat.com/browse/RHEL-49567
Co-authored-with: Tomáš Hozza <thozza@redhat.com>

Respect nspawn_args whenever doChroot is called

---

mock/py/mockbuild/util.py
releng/release-notes-next/buildroot-mounts-redundancy.bugfix

For more info poke at the commit message.

No per-command bootstrap mount leftovers

---

mock/py/mockbuild/backend.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/plugins/chroot_scan.py
releng/release-notes-next/unified-resultdir-preparation.bugfix

Fix the permissions for (re)created resultdir

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl
releng/release-notes-next/eln-repo-update.bugfix

ELN now has Pungi composes instead of OSBS, and are downloadable and mirrorable like other Fedora-hosted projects.  Also, with multilibs no longer being built, the mirrored conditional is no longer necessary.

configs: update ELN repos

---

mock/py/mockbuild/package_manager.py
releng/release-notes-next/dnf-to-dnf4-fallback-fix.bugfix

Fix the dnf -> dnf4 alias

---

mock/integration-tests/setup-box
mock/integration-tests/setup-playbook/README.md
mock/integration-tests/setup-playbook/spawn-test-machine-ec2.yaml

ci: how to setup custom testing machine

---

.github/workflows/python-diff-lint.yml
behave/README.md
behave/environment.py
behave/features/dnf4.feature
behave/features/environment.py
behave/features/steps/other.py
behave/pylintrc
behave/steps/other.py
behave/testlib.py
behave/testlib/__init__.py
behave/testlib/commands.py
behave/testlib/mock.py
pylintrc

behave: new test for dnf4 chroot without bootstrap

---

mock-core-configs/etc/mock/epel-10-aarch64.cfg
mock-core-configs/etc/mock/epel-10-ppc64le.cfg
mock-core-configs/etc/mock/epel-10-s390x.cfg
mock-core-configs/etc/mock/epel-10-x86_64.cfg
mock-core-configs/etc/mock/templates/centos-stream-10.tpl
mock-core-configs/etc/mock/templates/epel-10.tpl
releng/release-notes-next/epel10-metalinks.config.md

Previously the EPEL 10 config only included the koji local repo, because that was the only thing available at the time.  We now have working MirrorManager metalinks that we can use for the proper repos.  Now that we have those repos, we can set the koji local repo to disabled by default, matching earlier EPEL configs.
We also now have a koji symlink that will be updated over time to point to the latest minor version tag buildroot repo, which can be used in the koji local baseurl.  This avoids the inconvenience of updating that baseurl manually every six months.
Fixes: #1427

Add epel and epel-testing repos to the EPEL 10 config

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl
releng/release-notes-next/eln-bootstrap-image.bugfix

ELN now has Pungi composes instead of OSBS, and as a result, the bootstrap image pullspec has also changed.
This is a follow-up to #1473.
/cc @praiskup @sgallagher

configs: update ELN bootstrap image

---

.packit.yaml

The test-suite is not yet ready for F41
https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5

packit: keep testing F40 for now

---

mock-core-configs/etc/mock/templates/fedora-eln.tpl
releng/release-notes-next/eln-rs-removal.bugfix

The Fedora ELN ResilientStorage repositories are obsolete.
/cc @sgallagher

configs: remove ELN ResilientStorage repos

---

mock-core-configs/etc/mock/templates/centos-stream-10.tpl
releng/release-notes-next/use-non-development-centos-bootstrap-image.config.md

cc @carlwgeorge Who did the last commit using the development image for CentOS 10 Streams.

Use non development bootstrap image for CentOS Stream 10

---

mock/py/mockbuild/plugins/chroot_scan.py
releng/release-notes-next/chroot-scan-resultdir-creation.bugfix

In the real one now, also for the --chain method which is changing the buildroot.resultdir for every single package.  Previously, chroot_scan/ was (re)created for every --chain package in the basedir:
/var/lib/mock/fedora-41-x86_64/result/chroot_scan
Now, chroot_scan/ files are written into a package-specific resultdir, for example:
/var/tmp/mock-chain-root-28259-ie_33sdi/results/default/copr-cli-2.0-1.git.15.526473b.fc41/chroot_scan
/var/tmp/mock-chain-root-28259-ie_33sdi/results/default/python-copr-2.0-1.git.20.526473b.fc41/chroot_scan
This in turn fixes a --chain build, because it - together with the `chroo_scan` directory it created also `chroot_scan/..` directory, mistakenly root-owned.
Fixes: #1490

chroot_scan: create chroot_scan/ dir in buildroot.resultdir

---

.github/workflows/fedora-tox.yml
tox.ini

The version 3.7 is no longer available:
py37: skipped because could not find python interpreter with spec(s): py37

tox: add Python 3.13, drop 3.7

---

mock/mock.spec
releng/release-notes-next/sysusers-on-mageia.bugfix

The script for generating the %pre scriptlet is non-existing on new distributions (like Mageia now, but Fedora will drop that sooner or later, too).  The build of Mock on Mageia previously relied on sysusers.generate-pre.sh, and failed.
The sysusers feature is an RPM built-in anyway (on modern systems), so there's no reason to duplicate the logic in %pre.  Generate the %pre scriptlet only for older distributions.
Complements: #1367
Relates: #289
Relates: https://github.com/fedora-copr/copr/issues/2789

mock: avoid the %pre scriptlet if possible

---

.tito/tito.props
docs/Releasing-Mock.md

Historically, Tito only modified the Release tag for `--test` builds. Now, we also bump the Version field to ensure that Mock built from Git revisions always has a higher NVR than released packages.
https://github.com/rpm-software-management/tito/releases/tag/tito-0.6.27-1

releng: mock-from-git to have a higher NVR than released versions

---

docs/Plugin-CCache.md

The documentation was inconsistent, it stated the ccache plugin as both disabled by default (introduction) and enabled by default (configuration).
according to the code:
https://github.com/rpm-software-management/mock/blob/061d3b64ecce61826d3cbcbe9867a6eba35b9103/mock/py/mockbuild/config.py#L139..L148
The correct statement is disabled by default.
Also fix the configuration snippet accordingly.
Label `no-release-notes` seems appropriate.

Fix docs Plugin-CCache.md (not enabled by default)

---

behave/features/buildroot-image.feature
behave/steps/other.py
behave/testlib/mock.py
docs/Feature-buildroot-image.md
docs/Plugin-Export-Buildroot-Image.md
docs/index.md
mock/docs/mock.1
mock/docs/site-defaults.cfg
mock/mock.spec
mock/py/mock.py
mock/py/mockbuild/buildroot.py
mock/py/mockbuild/config.py
mock/py/mockbuild/package_manager.py
mock/py/mockbuild/plugins/buildroot_lock.py
mock/py/mockbuild/plugins/export_buildroot_image.py
mock/py/mockbuild/podman.py
releng/release-notes-next/export-import-oci-buildroot-image.feature

Fixes: #1482
[Exporting OCI image from buildroot](https://github.com/rpm-software-management/mock/blob/ce1037d392cbd7e68f10720ff7526afd90564dad/docs/Plugin-Export-Buildroot-Image.md)
[Using OCI image for initializing buildroot](https://github.com/rpm-software-management/mock/blob/ce1037d392cbd7e68f10720ff7526afd90564dad/docs/Feature-buildroot-image.md)

Generate / use OCI image for Mock buildroot

---

mock/docs/mock.1

When specifying an array with a single element using `--config-opts`, the user should specify the second item as empty, not the first:
Wrong:
```
$ mock --config-opts=foo= --config-opts=foo=bar --debug-config | grep foo
config_opts['foo'] = ['', 'bar']
```
Correct:
```
$ mock --config-opts=foo=bar --config-opts=foo= --debug-config | grep foo
config_opts['foo'] = ['bar']
```
The release notes where the feature was announced, Release-Notes-1.4.8.md, were correct but the man page was not.
I think this is probably `label no-release-notes`.

doc: `--config-opts` single-item array wants second to be blank

---

docs/Mock-Core-Configs.md
mock-core-configs/etc/mock/alma-kitten+epel-10-aarch64.cfg
mock-core-configs/etc/mock/alma-kitten+epel-10-ppc64le.cfg
mock-core-configs/etc/mock/alma-kitten+epel-10-s390x.cfg
mock-core-configs/etc/mock/alma-kitten+epel-10-x86_64.cfg
mock-core-configs/etc/mock/almalinux-kitten-10-aarch64.cfg
mock-core-configs/etc/mock/almalinux-kitten-10-ppc64le.cfg
mock-core-configs/etc/mock/almalinux-kitten-10-s390x.cfg
mock-core-configs/etc/mock/almalinux-kitten-10-x86_64.cfg
mock-core-configs/etc/mock/templates/almalinux-kitten-10.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/almakitten10+epel.config
releng/release-notes-next/almakitten10.config

This pull request adds the AlmaLinux Kitten 10 configs for Mock.
This requires https://github.com/rpm-software-management/distribution-gpg-keys/pull/128.

Add AlmaLinux Kitten 10 configs

---

docs/Mock-Core-Configs.md
mock-core-configs/etc/mock/azure-linux-2-aarch64.cfg
mock-core-configs/etc/mock/azure-linux-2-x86_64.cfg
mock-core-configs/etc/mock/azure-linux-3-aarch64.cfg
mock-core-configs/etc/mock/azure-linux-3-x86_64.cfg
mock-core-configs/etc/mock/kylin-10-aarch64.cfg
mock-core-configs/etc/mock/kylin-10-loongarch64.cfg
mock-core-configs/etc/mock/kylin-10-x86_64.cfg
mock-core-configs/etc/mock/templates/azure-linux-2.tpl
mock-core-configs/etc/mock/templates/azure-linux-3.tpl
mock-core-configs/etc/mock/templates/kylin-10.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/azure-linux-2.config
releng/release-notes-next/azure-linux-3.config
releng/release-notes-next/kylin-10.config

As mentioned in the openSUSE 15.6 merge request, we are moving everything to `mock` for building packages in NVIDIA. These are more configurations for additional distributions I had the "pleasure" to work on for supporting NVIDIA drivers  + CUDA:
- Kylin 10
- No OCI image used, as there's no official image available.
- Azure Linux 2
- Microsoft decided to rename it from CBL Mariner 2.0 (following Common Base Linux 1.0) mid lifecycle, so the repositories are called `mariner` and there's `cm2` as a `dist` tag.
- No OCI image used, it uses "`tiny dandified dnf`" as the package manager.
- Azure Linux 3
- No OCI image used, it uses "`tiny dandified dnf`" as the package manager.

Add Kylin 10, Azure Linux 2 and 3 configuration files

---

docs/Mock-Core-Configs.md

Just so that people can easily go from this page to the code of the actual config files.

docs: link the upstream mock-core-configs

---

behave/steps/other.py
docs/Plugin-BuildrootLock.md
mock/docs/buildroot-lock-schema-1.1.0.json
mock/py/mock-hermetic-repo.py
mock/py/mockbuild/plugins/buildroot_lock.py
mock/py/mockbuild/podman.py
mock/tests/test_buildroot_lock.py
releng/release-notes-next/hermetic-arch-specific.feature

hermetic: more image-pedantic work with bootstrap
When producing the buildroot lockfile, include additional bootstrap
image metadata that can be later used for a precise image pull.
The mock-hermetic-repo script is also modified here to respect the
additional metadata.  This allows us to, e.g., download bootstrap image
of a different (cross) architecture then the platform/host architecture
is.  In turn, the script is now fully arch-agnostic (any host arch may
be used for downloading files from any arch specific lockfile).
Closes: #1548

More strict hermetic image download

---

mock-core-configs/mock-core-configs.spec
releng/release-notes-next/oraclelinux-distro_id.config

Fixes: #1545
Expand Oracle Linux distro_id from `ol` to `oraclelinux` when looking for configuration files [issue#1545]

fix: expand Oracle Linux distro_id from ol to oraclelinux

---

mock/py/mockbuild/podman.py
releng/release-notes-next/podman-pull-fallback.bugfix

We retry the image pull with a `@backoff.on_predicate` wrapper, but it can still fail entirely. When that happens, `image_id` remains as `None` and this causes us to hit a subprocess exception in `tag_image`. Because the buildroot `_fallback` decorator only handles `PodmanError` exceptions, we blow up on that exception instead of falling back smoothly to chroot.
This solves that by giving the backoff wrapper an `on_giveup` handler that raises `PodmanError`, so the fallback mechanism should kick in.

podman: bail clearly when image pull fails

---

.github/workflows/Dockerfile
.github/workflows/docker-build.yml

CI: add docker build

---

mock-core-configs/etc/mock/templates/azure-linux-2.tpl
mock-core-configs/etc/mock/templates/azure-linux-3.tpl
releng/release-notes-next/azure-linux.config

Update the list of packages installed by default in the chroot to include `shadow-utils` so creating the `chroot` does not fail.
Due to recent changes, the `useradd/groupadd` commands are required by other packages in the list but the requirements are not specified correctly.

Update Azure Linux configurations

---

mock-core-configs/etc/mock/templates/epel-z-10.tpl
releng/release-notes-next/epel10-separate-templates.config

EPEL 10 "floating target" repo names have been implemented.  This adds a new epel-z-10 template that uses the names for the minor version tracking RHEL 10, and makes minor adjustments to the epel-10 template to use the names for the minor version tracking CentOS Stream 10.
Relates: #1427

Add epel-z-10 template

---

docs/Why-Mock.md

> rpm -rf %{?nonexisting}/
should be:
> rm -rf %{?nonexisting}/
Please add `label no-release-notes`.

Typo in docs/Why-Mock.md (label no-release-notes)

---

.packit.yaml
mock/integration-tests/setup-playbook/files/install-copr-packages

Fix TF package installation for tito --test versions

---

mock/py/mockbuild/util.py

`pretty_getcwd()` is called during module import (to set `ORIGINAL_CWD`), and using a traced function creates unwanted side effects.
Fixes: #1583
I think this can be `label no-release-notes`, let me know if you disagree.

Remove traceLog decorator from pretty_getcwd

---

mock/py/mockbuild/plugins/hw_info.py
releng/release-notes-next/hwinfo-plugin-memory-human.feature

I'm bit confused, when I tried to debug build failure - I expected the worker memory to be less than 4GB, I was surprised when I saw 256MB. As it turned out, it was 256GB actually, I converted the bytes
The `free` program prints values in kibibytes by default. Not in bytes, that more than expected without flags
This PR add's `--human` flag, so that the plugin output for storage and memory has the same units. Currently, such a flag is[ set for storage](https://github.com/rpm-software-management/mock/blob/main/mock/py/mockbuild/plugins/hw_info.py#L50)
> Show all output fields automatically scaled to shortest three digit unit and display the units of print out.  Following units are used:
**B** = bytes
**Ki** = kibibyte
**Mi** = mebibyte
**Gi** = gibibyte
**Ti** = tebibyte
**Pi** = pebibyte

feat: plugin: hw_info: added human-readable flag for memory info

---

.github/workflows/Dockerfile

This repo is regularly used for pre-release builds of Mock dependencies (e.g. distribution-gpg-keys, when waiting for updates-testing).

dockertest: enable @mock/mock-deps

---

mock/py/mockbuild/uid.py
releng/release-notes-next/python314.bugfix

Fixes: #1594
RHBZ#2372865
Previously, the default method of starting a process was fork. With Python3.14 it is no longer true (I think that default is spawner). But the new default does not work with Mock code and causes traceback:
```
Traceback (most recent call last):
File "/usr/libexec/mock/mock", line 1140, in <module>
main()
~~~~^^
File "/usr/lib/python3.14/site-packages/mockbuild/trace_decorator.py", line 93, in trace
result = func(*args, **kw)
File "/usr/libexec/mock/mock", line 718, in main
config_opts = uidManager.run_in_subprocess_without_privileges(
config.load_config, config_path, options.chroot)
File "/usr/lib/python3.14/site-packages/mockbuild/uid.py", line 183, in run_in_subprocess_without_privileges
return future.result()
~~~~~~~~~~~~~^^
File …
```

ProcessPoolExecutor changed behaviour with Python 3.14

---

mock-core-configs/etc/mock/rocky+epel-10-aarch64.cfg
mock-core-configs/etc/mock/rocky+epel-10-ppc64le.cfg
mock-core-configs/etc/mock/rocky+epel-10-s390x.cfg
mock-core-configs/etc/mock/rocky+epel-10-x86_64.cfg
mock-core-configs/etc/mock/rocky-10-aarch64.cfg
mock-core-configs/etc/mock/rocky-10-ppc64le.cfg
mock-core-configs/etc/mock/rocky-10-riscv64.cfg
mock-core-configs/etc/mock/rocky-10-s390x.cfg
mock-core-configs/etc/mock/rocky-10-x86_64.cfg
mock-core-configs/etc/mock/templates/rocky-10.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/rockylinux10.config

This PR adds in the Rocky Linux 10 mock configurations. Please let me know if I need to make any changes.
Related: https://github.com/rpm-software-management/distribution-gpg-keys/pull/139

Add Rocky Linux 10 mock configs

---

mock/py/mockbuild/config.py

No functional changes - just silencing a ResourceWarning by ensuring the file handle is explicitly closed.
ResourceWarning is typically ignored by default but some distributions enable it.
```
$ python -m pytest -Wdefault tests
...
mock/tests/test_config_loader.py::TestConfigLoader::test_config_paths
/home/me/mock/mock/py/mockbuild/config.py:722: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/me/mock/mock/tests/data/config-001/site-defaults.cfg' mode='r' encoding='UTF-8'>
content = open(config_file).read()
```
> or let us know to add `label no-release-notes` if you think the change does
> not deserve a release note.
I don't think this fix needs a release note.

Fix unclosed file warning

---

mock/py/mockbuild/installed_packages.py
mock/tests/test_buildroot_lock.py
releng/release-notes-next/buildroot-lock-err-reporting.feature

I've observed that we frequently encounter `annobin-docs.noarch` being reported as the missed package, presumably due to it being the first one alphabetically.  Let's modify the reporting to list all the missing packages instead.
Relates: https://github.com/rpm-software-management/dnf5/issues/1673

buildroot_lock: better error reporting

---

mock-core-configs/etc/mock/fedora-43-aarch64.cfg
mock-core-configs/etc/mock/fedora-43-i386.cfg
mock-core-configs/etc/mock/fedora-43-ppc64le.cfg
mock-core-configs/etc/mock/fedora-43-s390x.cfg
mock-core-configs/etc/mock/fedora-43-x86_64.cfg
mock-core-configs/etc/mock/fedora-44-aarch64.cfg
mock-core-configs/etc/mock/fedora-44-i386.cfg
mock-core-configs/etc/mock/fedora-44-ppc64le.cfg
mock-core-configs/etc/mock/fedora-44-s390x.cfg
mock-core-configs/etc/mock/fedora-44-x86_64.cfg
mock-core-configs/etc/mock/templates/fedora-eln.tpl
mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
mock-core-configs/mock-core-configs.spec
releng/release-notes-next/fedora-43-branching.feature

Set:    rawhide == Fedora 44
Move:   42 => 43
Arches: aarch64 i386 ppc64le s390x x86_64
WARNING: Make sure Fedora Copr maintainers are informed that
WARNING: they should run 'copr-frontend branch-fedora 43'.
WARNING: That has to be done right on time when branching is done.
WARNING: Please check that distribution-gpg-keys have the N+1 key,
you likely want to bump Requires: distribution-gpg-keys!

Move Rawhide to F44

---

.github/pull_request_template.md

Previous markup showed almost everything as H1. This is less agressive if users do not delete the comments.

fix markup in pull_request_template

---

mock/py/mock-hermetic-repo.py
releng/release-notes-next/mock-hermetic-repo-client-cert.feature

- in some rare cases, a mock config can include a yum repo config section that include a ssl cert and key that are used for authentication by dnf
- when running mock-hermetic-repo, the same client cert is needed to download the rpms.
- this commit adds support for the following:
```
--client-cert-for example.com /path/crt.pem /path/key.pem
```
Assisted-by: Cursor
> Add a reference to related issue - preferably in the git commit message
Fixes: #NUMBER
> Add release note. See https://rpm-software-management.github.io/mock/Release-Notes-New-Entry
> or let us know to add `label no-release-notes` if you think the change does
> not deserve a release note.

feat: add support for client certificates
