py/mockbuild/buildroot.py
=> Remove tmpdirs regardless of buildroot existence

etc/mock/mageia-6-armv5tl.cfg, etc/mock/mageia-6-armv7hl.cfg, etc/mock/mageia-6-i586.cfg, etc/mock/mageia-6-x86_64.cfg, etc/mock/mageia-cauldron-armv5tl.cfg, etc/mock/mageia-cauldron-armv7hl.cfg, etc/mock/mageia-cauldron-i586.cfg, etc/mock/mageia-cauldron-x86_64.cfg
This mimics what the official build system does...
=> Add %distro_section macro to Mageia targets

mock-core-configs/mock-core-configs.spec, mock/mock.spec
This PR includes fixes to the mock and mock-core-configs spec files to support targeting Mageia.
=> Mageia support in the mock/mock-core-configs specs

mock/etc/mock/site-defaults.cfg, mock/py/mockbuild/util.py
=> New config option 'opstimeout' has been added.

mock/docs/mock.1, mock/py/mock.py, mock/py/mockbuild/backend.py
add support for .spec in --installdeps #43
=> add support for .spec in --installdeps

mock/etc/mock/site-defaults.cfg, mock/py/mock.py, mock/py/mockbuild/plugins/root_cache.py, mock/py/mockbuild/scm.py, mock/py/mockbuild/util.py
Resolves: #169 
@praiskup @Conan-Kudo  what about this one?
=> add support for bsdtar

mock/py/mockbuild/scm.py
=> Remove percent signs from format string

mock-core-configs/etc/mock/fedora-29-aarch64.cfg, mock-core-configs/etc/mock/fedora-29-armhfp.cfg, mock-core-configs/etc/mock/fedora-29-i386.cfg, mock-core-configs/etc/mock/fedora-29-ppc64.cfg, mock-core-configs/etc/mock/fedora-29-ppc64le.cfg, mock-core-configs/etc/mock/fedora-29-s390x.cfg, mock-core-configs/etc/mock/fedora-29-x86_64.cfg, mock-core-configs/etc/mock/fedora-30-aarch64.cfg, mock-core-configs/etc/mock/fedora-30-armhfp.cfg, mock-core-configs/etc/mock/fedora-30-i386.cfg, mock-core-configs/etc/mock/fedora-30-ppc64.cfg, mock-core-configs/etc/mock/fedora-30-ppc64le.cfg, mock-core-configs/etc/mock/fedora-30-s390x.cfg, mock-core-configs/etc/mock/fedora-30-x86_64.cfg, mock-core-configs/etc/mock/fedora-rawhide-aarch64.cfg, mock-core-configs/etc/mock/fedora-rawhide-armhfp.cfg, mock-core-configs/etc/mock/fedora-rawhide-i386.cfg, mock-core-configs/etc/mock/fedora-rawhide-ppc64.cfg, mock-core-configs/etc/mock/fedora-rawhide-ppc64le.cfg, mock-core-configs/etc/mock/fedora-rawhide-s390x.cfg, mock-core-configs/etc/mock/fedora-rawhide-x86_64.cfg, mock-core-configs/mock-core-configs.spec
Prepare for a branching. This should be merged on a branching day.
=> add fedora 29 configs and change rawhide to F30

mock/py/mockbuild/backend.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> Do raise exception if no dynamic deps, but build failed

mock/etc/mock/site-defaults.cfg, mock/py/mockbuild/backend.py, mock/py/mockbuild/util.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> Update dynamic BuildRequires code to support --nodeps

mock/docs/mock.1, mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/exception.py, mock/py/mockbuild/package_manager.py, mock/py/mockbuild/plugins/package_state.py, mock/py/mockbuild/rebuild.py, mock/py/mockbuild/util.py, mock/py/mockchain.py, mock/tests/09-mockchain-fail.tst, mock/tests/10-mockchain-partial.tst, mock/tests/11-mockchain-success.tst, mock/tests/12-mockchain-recurse.tst, mock/tests/testenvironment
This PR is created to merge mockain.py to mock.py
=> merge mockchain to mock

mock/docs/mock.1
See https://github.com/rpm-software-management/mock/issues/255
=> Update the man page about ~/.config/mock/FOO.cfg

mock/py/mockbuild/backend.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> Fix compatibility with pre-4.15 RPM versions with DynamicBuildRequires

mock-core-configs/etc/mock/openmandriva-4.0-aarch64.cfg, mock-core-configs/etc/mock/openmandriva-4.0-armv7hnl.cfg, mock-core-configs/etc/mock/openmandriva-4.0-i686.cfg, mock-core-configs/etc/mock/openmandriva-4.0-x86_64.cfg, mock-core-configs/etc/mock/openmandriva-cooker-aarch64.cfg, mock-core-configs/etc/mock/openmandriva-cooker-armv7hnl.cfg, mock-core-configs/etc/mock/openmandriva-cooker-i686.cfg, mock-core-configs/etc/mock/openmandriva-cooker-x86_64.cfg, mock-core-configs/etc/mock/openmandriva-rolling-aarch64.cfg, mock-core-configs/etc/mock/openmandriva-rolling-armv7hnl.cfg, mock-core-configs/etc/mock/openmandriva-rolling-i686.cfg, mock-core-configs/etc/mock/openmandriva-rolling-x86_64.cfg
Requires https://github.com/xsuchy/distribution-gpg-keys/pull/20
=> Add initial OpenMandriva distribution targets

mock/py/mockbuild/plugins/hw_info.py, mock/py/mockbuild/plugins/root_cache.py, mock/py/mockbuild/util.py
Signed-off-by: @berolinux 
Signed-off-by: @Conan-Kudo
=> Fix binary locations in /bin for split-usr setups

mock/etc/mock/site-defaults.cfg, mock/py/mock.py, mock/py/mockbuild/util.py
=> Removing buildstderr from log

mock/py/mockbuild/plugins/root_cache.py
=> Applying patch for bsdtar

mock/mock.spec, mock/py/mock-parse-buildlog.py
=> Adding tool for parsing build.log

mock-core-configs/etc/mock/fedora-29-aarch64.cfg, mock-core-configs/etc/mock/fedora-29-armhfp.cfg, mock-core-configs/etc/mock/fedora-29-i386.cfg, mock-core-configs/etc/mock/fedora-29-ppc64le.cfg, mock-core-configs/etc/mock/fedora-29-s390x.cfg, mock-core-configs/etc/mock/fedora-29-x86_64.cfg, mock-core-configs/etc/mock/fedora-30-aarch64.cfg, mock-core-configs/etc/mock/fedora-30-armhfp.cfg, mock-core-configs/etc/mock/fedora-30-i386.cfg, mock-core-configs/etc/mock/fedora-30-ppc64le.cfg, mock-core-configs/etc/mock/fedora-30-s390x.cfg, mock-core-configs/etc/mock/fedora-30-x86_64.cfg
Partially resolve #296, I didn't add to ```rawhide``` and ```31``` because I don't have the repos configs for ```updates-modular``` of ```rawhide```
=> added updates-modular to 29 and 30

mock/docs/mock-parse-buildlog.1, mock/mock.spec
Depends on: https://github.com/rpm-software-management/mock/pull/291
=> Documentation for build.log parser

mock/py/mockbuild/mounts.py, mock/py/mockbuild/plugins/selinux.py, mock/py/mockbuild/util.py
See the commit message for more info.
=> mock: make only /proc and /sys "rprivate"

mock/etc/mock/site-defaults.cfg
=> Resultdir variable is missing in config.

mock-core-configs/etc/mock/epel-6-x86_64.cfg, mock-core-configs/etc/mock/epel-7-aarch64.cfg, mock-core-configs/etc/mock/epel-7-ppc64le.cfg, mock-core-configs/etc/mock/epel-7-x86_64.cfg
=> adds equation sign to --disablerepo

mock/docs/mock.1, mock/py/mock.py, mock/py/mockbuild/util.py
This is a follow-up for PR#342.
=> add commandline options for using bootstrap image

mock/py/mockbuild/backend.py, mock/py/mockbuild/util.py
=> chain: propagate local repository to bootstrap chroot

mock/etc/mock/site-defaults.cfg, mock/py/mockbuild/package_manager.py, mock/py/mockbuild/util.py
=> mock: options for retrying packager managers' actions

mock/mock.spec, mock/mockchain, mock/py/mockchain.py
=> mockchain wrapper

mock/py/mockbuild/backend.py
=> chain: success/fail files shouldn't be root owned

mock-core-configs/etc/mock/epel-6-i386.cfg, mock-core-configs/etc/mock/epel-6-ppc64.cfg, mock-core-configs/etc/mock/epel-6-x86_64.cfg, mock-core-configs/etc/mock/epel-7-aarch64.cfg, mock-core-configs/etc/mock/epel-7-ppc64.cfg, mock-core-configs/etc/mock/epel-7-ppc64le.cfg, mock-core-configs/etc/mock/epel-7-x86_64.cfg, mock-core-configs/etc/mock/templates/centos-8.tpl
=>  Adds missing metadata_epire=0 in epel chroots

mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/rebuild.py
=> buildsrpm should have --sources as optional

mock/py/mockbuild/buildroot.py, mock/py/mockbuild/podman.py
=> Fix bootstrap image

mock/py/mockbuild/util.py
=> Delete is_statement variable to simplify the code

mock/py/mockbuild/buildroot.py
We would ideally --bind mount
/var/lib/mock/fedora-rawhide-x86_64/root/dev/loop-control
into
/dev/loop-control
But, there are currently two issues with nspawn:
- the src path is sub-directory of 'systemd-nspawn -D', and thus
systemd-nspawn thinks the file doesn't exist (I suppose it overmounts
the /dev subidrectory before trying to do the bind-mount)
- there's the default DeviceAllow=/dev rule
Ideas?
=> mock: loop devices in nspawn

mock/py/mock.py
=> mock: use systemd-nspawn --pipe argument

mock/py/mockbuild/package_manager.py
=> mock: bind mount local repos to bootstrap chroot

mock-core-configs/etc/mock/rhel-7-aarch64.cfg, mock-core-configs/etc/mock/rhel-7-ppc64.cfg, mock-core-configs/etc/mock/rhel-7-ppc64le.cfg, mock-core-configs/etc/mock/rhel-7-s390x.cfg, mock-core-configs/etc/mock/rhel-7-x86_64.cfg, mock-core-configs/etc/mock/rhel-8-ppc64.cfg, mock-core-configs/etc/mock/rhel-8-s390x.cfg, mock-core-configs/etc/mock/templates/rhel-7.tpl
=> fixup rhel non-x86_64 architectures

mock-core-configs/etc/mock/templates/custom-1.tpl, mock/etc/mock/site-defaults.cfg, mock/py/mock.py, mock/py/mockbuild/util.py
And update the in-code documentation to better describe the difference
between use_bootstrap and use_bootstrap_image, and when one may want to
use them.
Fixes: #458
=> mock: rename use_bootstrap_container to use_bootstrap

mock/py/mockbuild/util.py, mock/tests/test_config_templates.py
=> mock: keep trailing newlines in jinja expand

mock/mock.spec
=> mock: exclude also compiled stuff packaged in sub-packages

mock/py/mockbuild/package_manager.py
=> mock: add config options for optionally copying /etc/pki files from host

mock/integration-tests/05-orphanskill-std.tst, mock/py/mockbuild/backend.py
=> mock: fix --chain --isolation=simple with URLs

mock/py/mockbuild/buildroot.py
The problem in GH#539 is that _resetLogging() is called twice initially
(for both bootstrap and target chroot) so it always initially
(force=False) adds two FileHandlers to the _same_ logger objects.  And
bad things happened when both the handlers were instructed to write to
the same file.
It's not ideal time to resolve the logging mess properly (that will be
large and risky patch), so I have at least work-around that should
minimize the logging problems.
Related: #539
=> bootstrap: provide predictable resultdir

mock/py/mockbuild/package_manager.py, mock/tests/test_package_manager.py
https://bugzilla.redhat.com/1815703
https://bugzilla.redhat.com/1816696
=> Better mounting of local repositories to bootstrap

mock/py/mockbuild/backend.py
There were two more issues in dynamic_buildrequires handler.  First that
we set success=True anytime `rpmbuild -br` succeeded.  This would exit
the build requires loop too early if `-br` eventually returned exit
status 0.
The second is that we tried to install the nosrc.rpm file in finally
block, which was done everytime the `rpmbuild -br` command failed (not
only when exit status was 0 or 11).
Fixes: #570, #581
=> Better error for dynamic_buildrequires %prep failure

mock/py/mockbuild/util.py
=> Don't change the dict while iterating over it

mock/docs/site-defaults.cfg
=> document which packages we need in buildroot

mock/py/mock.py
this was left over after commit 8d0c3ad5ddc36d4f7649cc1097de003db2219a0b
Doing just these small changes becouse I am showing my nephew how development works. :)
=> unused import

mock-core-configs/etc/mock/fedora-eln-aarch64.cfg, mock-core-configs/etc/mock/fedora-eln-armhfp.cfg, mock-core-configs/etc/mock/fedora-eln-i386.cfg, mock-core-configs/etc/mock/fedora-eln-ppc64le.cfg, mock-core-configs/etc/mock/fedora-eln-s390x.cfg, mock-core-configs/etc/mock/fedora-eln-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl
=> configs: add Fedora ELN support

mock/py/mock-parse-buildlog.py, mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/package_manager.py, mock/py/mockbuild/scm.py, mock/py/mockbuild/util.py
=> addressing various pylint warnings

behave/features/add-repo.feature, behave/features/cmdline-errors.feature, behave/features/environment.py, behave/features/steps/other.py, behave/testlib.py, mock/docs/mock.1, mock/docs/release-instructions.txt, mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/util.py
Plus several other minor things I spotted when I experimented with the fixes.
https://bugzilla.redhat.com/show_bug.cgi?id=1857918
=> Mostly --addrepo/-a fixes

mock-core-configs/etc/mock/templates/epelplayground-8.tpl
=> EPEL Playground do depend on normal EPEL

mock-core-configs/etc/mock/centos-6-i386.cfg, mock-core-configs/etc/mock/centos-6-x86_64.cfg, mock-core-configs/etc/mock/centos-7-aarch64.cfg, mock-core-configs/etc/mock/centos-7-ppc64.cfg, mock-core-configs/etc/mock/centos-7-ppc64le.cfg, mock-core-configs/etc/mock/centos-7-x86_64.cfg, mock-core-configs/etc/mock/centos-8-aarch64.cfg, mock-core-configs/etc/mock/centos-8-ppc64le.cfg, mock-core-configs/etc/mock/centos-8-x86_64.cfg, mock-core-configs/etc/mock/epel-6-x86_64.cfg, mock-core-configs/etc/mock/templates/centos-6.tpl, mock-core-configs/etc/mock/templates/centos-7.tpl, mock-core-configs/etc/mock/templates/epel-6.tpl, mock-core-configs/etc/mock/templates/epel-7.tpl, mock-core-configs/etc/mock/templates/epel-8.tpl
=> Provide plain CentOS configs without EPEL

mock/mock.spec, mock/py/mock.py
=> Log mock's NVR

mock/integration-tests/20-lvm-plugin.tst, mock/integration-tests/25-postupdate-root-cache.tst, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/plugins/lvm_root.py, mock/py/mockbuild/plugins/root_cache.py
=> Create new root cache tarball or LVM snapshot after updating the chroot

mock/py/mockbuild/exception.py, mock/py/mockbuild/util.py
=> move commandTimeoutExpired to exception module and give it result code 11

mock/py/mockbuild/buildroot.py, mock/py/mockbuild/util.py
=> Allow %-sign in config_opts['resultdir']

mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/file_downloader.py, mock/py/mockbuild/plugins/root_cache.py, mock/py/mockbuild/text.py, mock/py/mockbuild/util.py, mock/tests/test_config_templates.py, mock/tests/test_package_manager.py
because of its length. See details in two commits.
=> move things out of util.py

mock/py/mockbuild/util.py
=> Fix addrepo when repo is missing

mock/py/mockbuild/util.py
The '/bin/sh -i -l' calls setsid(), and if we do that right before
call([sh, -i, -l]), the subsequent setsid fails:
Start: shell
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
=> doshell: don't setsid() twice

mock/py/mockbuild/backend.py
=> early error when bootstrap is off and external buildrequires are detected

mock/py/mockbuild/buildroot.py
=> bootstrap: copy in katello CA pem file if exists

mock-core-configs/etc/mock/templates/centos-8.tpl
following
https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
=> rename repoid for centos8

mock-core-configs/etc/mock/templates/fedora-eln.tpl, releng/rawhide-branching.sh
Related discussions:
https://pagure.io/releng/issue/10007
https://github.com/fedora-eln/eln/issues/28
https://bugzilla.redhat.com/show_bug.cgi?id=1931095
Fixes: #702
=> configs: use Fedora N-1 gpg keys for ELN

mock-core-configs/etc/mock/templates/fedora-eln.tpl
See Fedora change: https://fedoraproject.org/wiki/Changes/Remove_make_from_BuildRoot
@mmathesius please ack
=> Remove make from default ELN buildroot

mock/py/mockbuild/buildroot.py
=> Pre-create the dest directory in _copy_config

mock/docs/mock.1, mock/py/mockbuild/backend.py, mock/py/mockbuild/util.py
Additionally change to `chroothome` when --shell.
Relates: #693
=> honor --cwd for --shell

mock-core-configs/etc/mock/templates/centos-7.tpl, mock-core-configs/etc/mock/templates/centos-8.tpl, mock-core-configs/etc/mock/templates/centos-stream-8.tpl
https://github.com/containers/shortnames/pull/23
=> Switch CentOS templates to use quay.io images for bootstrap

mock-core-configs/etc/mock/almalinux-8-aarch64.cfg, mock-core-configs/etc/mock/templates/almalinux-8.tpl
This PR includes a couple of improvements for AlmaLinux:
* Add Devel repo for unshipped content, default to disabled
* Add AArch64 target to build for 64-bit ARM
=> AlmaLinux config improvements

mock-core-configs/etc/mock/rhel+epel-8-aarch64.cfg, mock-core-configs/etc/mock/rhel+epel-8-ppc64.cfg, mock-core-configs/etc/mock/rhel+epel-8-ppc64le.cfg, mock-core-configs/etc/mock/rhel+epel-8-x86_64.cfg
This makes it clear that this is a combination rather than some
distinct configuration.
=> config: Rename rhelepel-8-* configs to rhel+epel-8-*

mock-core-configs/etc/mock/templates/centos-8.tpl, mock-core-configs/etc/mock/templates/centos-stream-8.tpl, mock-core-configs/etc/mock/templates/epel-8.tpl
Removed failovermethod=priority as this is removed from dnf lately.
=> remove failovermethod=priority for dnf repos

mock-core-configs/etc/mock/centos-stream+epel-next-9-aarch64.cfg, mock-core-configs/etc/mock/centos-stream+epel-next-9-ppc64le.cfg, mock-core-configs/etc/mock/centos-stream+epel-next-9-s390x.cfg, mock-core-configs/etc/mock/centos-stream+epel-next-9-x86_64.cfg
This allows people to build against EPEL Next 9.
Fixes #821.
=> config: Add CentOS Stream 9 + EPEL Next 9

docs/Release-Notes-2.16.md
=> add Release-Notes-2.16

mock/py/mockbuild/util.py
It happened several times before that the software inside container hit
the systemd-nspawn's seccomp filters.  It is proven to cause troubles,
and the filter updates take some time.
It is not the purpose of Mock to provide full isolation (see "Scope"
in https://rpm-software-management.github.io/mock/ and the notes about
isolation), and thus it looks it should be OK to disable this feature.
Fixes: #811
=> nspawn: disable system call filtering

mock-core-configs/mock-core-configs.spec, mock/mock.spec, mock/py/mockbuild/util.py
There are more. I picked up these trivial, where I do not expect much discussion.
See individual commits - all but one are reverts.
This should be merged after #838
=> removing el7 workarounds

mock-core-configs/mock-core-configs.spec
We need this commit:
https://github.com/xsuchy/distribution-gpg-keys/commit/00cf7be697ef9a93724fb01110929a30400ddac7
=> configs: depend on distribution-gpg-keys 1.63

mock-core-configs/etc/mock/fedora-36-aarch64.cfg, mock-core-configs/etc/mock/fedora-36-armhfp.cfg, mock-core-configs/etc/mock/fedora-36-i386.cfg, mock-core-configs/etc/mock/fedora-36-ppc64le.cfg, mock-core-configs/etc/mock/fedora-36-s390x.cfg, mock-core-configs/etc/mock/fedora-36-x86_64.cfg, mock-core-configs/etc/mock/fedora-37-aarch64.cfg, mock-core-configs/etc/mock/fedora-37-armhfp.cfg, mock-core-configs/etc/mock/fedora-37-i386.cfg, mock-core-configs/etc/mock/fedora-37-ppc64le.cfg, mock-core-configs/etc/mock/fedora-37-s390x.cfg, mock-core-configs/etc/mock/fedora-37-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl, mock-core-configs/etc/mock/templates/fedora-rawhide.tpl, mock-core-configs/mock-core-configs.spec
Done by `$ ./releng/rawhide-branching.sh`.
Branching is very close:
https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html
=> configs: Fedora 36 branching

mock-core-configs/etc/mock/chroot-aliases.cfg, mock-core-configs/etc/mock/eol/centos+epel-8-aarch64.cfg, mock-core-configs/etc/mock/eol/centos+epel-8-ppc64le.cfg, mock-core-configs/etc/mock/eol/centos+epel-8-x86_64.cfg, mock-core-configs/etc/mock/eol/centos-8-aarch64.cfg, mock-core-configs/etc/mock/eol/centos-8-ppc64le.cfg, mock-core-configs/etc/mock/eol/centos-8-x86_64.cfg, mock-core-configs/etc/mock/eol/templates/centos-8.tpl
Also migrate to vault baseurls.
=> configs: move CentOS/EPEL 8 configs to eol/

mock-core-configs/etc/mock/fedora-37-armhfp.cfg, mock-core-configs/etc/mock/fedora-rawhide-armhfp.cfg
https://fedoraproject.org/wiki/Changes/RetireARMv7
=> Delete Fedora 37/Rawhide armhfp configs

mock/py/mockbuild/plugins/hw_info.py
=> add cachedir to output of hw_info plugin

mock-core-configs/etc/mock/chroot-aliases.cfg, mock-core-configs/etc/mock/epel-9-aarch64.cfg, mock-core-configs/etc/mock/epel-9-ppc64le.cfg, mock-core-configs/etc/mock/epel-9-s390x.cfg, mock-core-configs/etc/mock/epel-9-x86_64.cfg, mock-core-configs/etc/mock/rhel+epel-9-aarch64.cfg, mock-core-configs/etc/mock/rhel+epel-9-ppc64le.cfg, mock-core-configs/etc/mock/rhel+epel-9-s390x.cfg, mock-core-configs/etc/mock/rhel+epel-9-x86_64.cfg, mock-core-configs/etc/mock/rhel-9-aarch64.cfg, mock-core-configs/etc/mock/rhel-9-ppc64le.cfg, mock-core-configs/etc/mock/rhel-9-s390x.cfg, mock-core-configs/etc/mock/rhel-9-x86_64.cfg, mock-core-configs/etc/mock/templates/rhel-9.tpl, mock-core-configs/mock-core-configs.spec
Depends on https://github.com/xsuchy/distribution-gpg-keys/pull/63 to be merged first.
=> Add RHEL9 templates and configs

mock-core-configs/etc/mock/eurolinux-9-aarch64.cfg, mock-core-configs/etc/mock/eurolinux-9-i686.cfg, mock-core-configs/etc/mock/eurolinux-9-x86_64.cfg, mock-core-configs/etc/mock/templates/eurolinux-9.tpl
EuroLinux 9 mock chroot config.
Tagging @AlexBaranowski for review.
=> EuroLinux 9 chroot config

docs/index.md
We added an important description about the release
=> Added description of 1.4.1 release notes :)

mock-core-configs/etc/mock/templates/fedora-eln.tpl
This package doesn't appear to be available in ELN repos.
=> config: Fedora ELN fixes

mock/py/mockbuild/util.py
=> mock: typo in the subscription error message

mock-core-configs/etc/mock/openeuler-22.03-aarch64.cfg, mock-core-configs/etc/mock/openeuler-22.03-x86_64.cfg, mock-core-configs/etc/mock/templates/openeuler-22.03.tpl, mock-core-configs/mock-core-configs.spec
This patch adds the mock template and config for openEuler 22.03.
=> Add openEuler 22.03 support

docs/Plugin-BindMount.md
follow up of 72a558eb80ebd3ff3509e9ab7e3ac8ca94b49ca2
resolves: #971
=> document bind mounting files

mock/py/mockbuild/backend.py
=> mock: don't use rpmbuild --noclean option if not supported

mock/mock.spec
=> mock-scm: recommend rpkg-util

mock/docs/site-defaults.cfg, mock/py/mock.py, mock/py/mockbuild/config.py
=> check for target specific qemu-user-static

mock/docs/site-defaults.cfg, mock/py/mock.py, mock/py/mockbuild/config.py
Relates:
https://bugzilla.redhat.com/show_bug.cgi?id=2143069
https://bodhi.fedoraproject.org/updates/FEDORA-2022-389622bd06
=> Better checking for qemu user static binaries

mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl, mock-core-configs/mock-core-configs.spec
=> update gpg keys for Tumbleweed

mock-core-configs/etc/mock/templates/centos-stream-8.tpl
=> new URL for CenOS Stream 8 koji

mock/py/mock.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/mounts.py, mock/py/mockbuild/package_manager.py, mock/py/mockbuild/uid.py
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2166028
=> mock: essential mounts are not visible when installing through bootstrap

docs/index.md, mock/py/mock.py, mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py, mock/py/mockbuild/package_manager.py, mock/py/mockbuild/podman.py
=> Make --use-bootstrap-image work in containers

mock/py/mockbuild/backend.py
=> Stop producing long rpmbuild --help output in logs

mock/py/mockbuild/backend.py, mock/py/mockbuild/buildroot.py
Relates: https://pagure.io/releng/issue/11446
=> mock: dump every package manager command to root log

mock/py/mockbuild/plugin.py
Fixes https://github.com/rpm-software-management/mock/issues/1140
I have not tested this, hence marking it as a draft.
=> Python 3.12 compatibility: Replace the removed imp module with importlib

docs/Feature-rhelchroots.md
Simple Content Access (SCA) makes configuring a RHEL subscription for mock much easier.  Update the documentation to describe setup both with and without SCA.
=> Update RHEL subscription instructions for SCA

mock/py/mockbuild/backend.py
Should fix bugs like:
https://bugzilla.redhat.com/2169055
https://bugzilla.redhat.com/2176689
https://bugzilla.redhat.com/2176691
https://bugzilla.redhat.com/2177680
https://bugzilla.redhat.com/2181641
=> Kill remaining processes before cleaning-up the chroot

.reuse/dep5
I followed https://reuse.software/spec/#dep5
=> add REUSE description of licenses

mock-core-configs/etc/mock/fedora-39-aarch64.cfg, mock-core-configs/etc/mock/fedora-39-i386.cfg, mock-core-configs/etc/mock/fedora-39-ppc64le.cfg, mock-core-configs/etc/mock/fedora-39-s390x.cfg, mock-core-configs/etc/mock/fedora-39-x86_64.cfg, mock-core-configs/etc/mock/fedora-40-aarch64.cfg, mock-core-configs/etc/mock/fedora-40-i386.cfg, mock-core-configs/etc/mock/fedora-40-ppc64le.cfg, mock-core-configs/etc/mock/fedora-40-s390x.cfg, mock-core-configs/etc/mock/fedora-40-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl, mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
The actual branching happens 2023-08-08.
=> Branch Fedora 39 from Rawhide

docs/Release-Notes-Next.md, mock/mock.spec
Per https://rpm-software-management.github.io/mock/Releasing-Mock
=> Post-release administrivia

mock/py/mockbuild/buildroot.py, mock/py/mockbuild/file_util.py
=> Drop /etc/rpm/macros.image-language-conf from bootstrap images

mock/py/mockbuild/podman.py
Relates: https://github.com/containers/podman/issues/19717
Resolves: https://github.com/fedora-copr/copr/issues/2875
Needs to be applied on top of #1196
=> podman: assert that pulled image has "native" arch     

mock/docs/mock.1
=> man: better --config-opts array specification

mock/py/mockbuild/buildroot.py
Because resultdir is, by default, created below basedir.  This has been breaking use-cases started with commands.init(do_log=True).
The bug was caused by f7b0c9bf18c46046be922adc740d1c6616ae0cc6, where we started pre-creating resuldir sooner than before so we could start the logging early.
Fixes: #1183
Complements: f7b0c9bf18c46046be922adc740d1c6616ae0cc6
=> Assure basedir exists before creating resultdir

mock/py/mockbuild/backend.py, mock/py/mockbuild/mounts.py, mock/py/mockbuild/util.py, releng/release-notes-next/postinstall-exit-status.feature
The Answer to the Ultimate Question of Life, the Universe, and Everything is #42.
=> Fail mock process if DNF in --postinstall fails

mock/README.md
https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/thread/HIHEAEWY6MEZDK23EY4YXDRL5FJIOT5A/
=> Migrate from IRC to Matrix

mock/integration-tests/daemontest.c, mock/py/mockbuild/util.py, releng/release-notes-next/better-orphankill-report.feature
=> orphanskill: log command line arguments of the terminated process

mock-core-configs/etc/mock/fedora-40-aarch64.cfg, mock-core-configs/etc/mock/fedora-40-i386.cfg, mock-core-configs/etc/mock/fedora-40-ppc64le.cfg, mock-core-configs/etc/mock/fedora-40-s390x.cfg, mock-core-configs/etc/mock/fedora-40-x86_64.cfg, mock-core-configs/etc/mock/fedora-41-aarch64.cfg, mock-core-configs/etc/mock/fedora-41-i386.cfg, mock-core-configs/etc/mock/fedora-41-ppc64le.cfg, mock-core-configs/etc/mock/fedora-41-s390x.cfg, mock-core-configs/etc/mock/fedora-41-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl, mock-core-configs/etc/mock/templates/fedora-rawhide.tpl, mock-core-configs/mock-core-configs.spec, releng/rawhide-branching.sh, releng/release-notes-next/fedora-40-branching.feature
Branching event planned for the next week, 2024-02-13: https://fedorapeople.org/groups/schedule/f-40/f-40-all-tasks.html
Relates: #1307
Command: ./releng/rawhide-branching.sh
=> Branch Fedora 41

mock/etc/bash_completion.d/mock, releng/release-notes-next/greedy-options-bash-completion.bugfix
=> Handle greedy options in Bash completion

docs/Plugin-ChrootScan.md, mock/docs/site-defaults.cfg, mock/py/mockbuild/config.py, mock/py/mockbuild/plugins/chroot_scan.py, releng/release-notes-next/chroot_scan_tarball.feature
Motivated by https://pagure.io/koji/issue/3439
=> Allow chroot_scan to create archive instead of directory

.tito/packages/mock-core-configs, docs/Release-Notes-Configs-40.3.md, docs/Releasing-Mock.md, docs/index.md, mock-core-configs/mock-core-configs.spec, releng/generate-release-notes, releng/release-notes-next/c10s.config, releng/release-notes-next/fedora-branched-no-modular.config, releng/release-notes-next/fedora-rawhide-no-modular.config, releng/release-notes-next/opensuse-repo-arch.config
My first release in quite some time, please rather take a look.
=> Configs release 40.3

.tito/releasers.conf, docs/Releasing-Mock.md, mock-core-configs/mock-core-configs.spec, mock/mock.spec
Some changes I made when releasing https://rpm-software-management.github.io/mock/Release-Notes-5.6
=> Post release fixes

mock/mock.spec, releng/release-notes-next/docdir-ownership.bugfix
=> own /usr/share/doc/mock

.tito/packages/mock-core-configs, docs/Release-Notes-Configs-40.6.md, docs/index.md, mock-core-configs/mock-core-configs.spec, releng/release-notes-next/c10s-compose.config
Created by command:
/usr/bin/tito tag
=> configs: release v40.6

mock-core-configs/etc/mock/templates/centos-stream-10.tpl, releng/release-notes-next/c10s-metalink.config
This is a followup for 9e596290d367094f56d612fe5e715094682710b0
=> Use metalinks for c10s {baseos,appstream,crb}-{source,debuginfo}

docs/Plugin-CCache.md
=> document hashdir in ccache plugin

releng/release-notes-next/hashdir.feature
=> Fix hashdir release notes snippet wording

mock-core-configs/etc/mock/openeuler-24.03-aarch64.cfg, mock-core-configs/etc/mock/openeuler-24.03-x86_64.cfg, mock-core-configs/etc/mock/templates/openeuler-24.03.tpl, releng/release-notes-next/add-openeuler-2403.config
Configs for openEuler 24.03 LTS based on
mock-core-configs/etc/mock/templates/openeuler-22.03.tpl
mock-core-configs/etc/mock/openeuler-22.03-aarch64.cfg
mock-core-configs/etc/mock/openeuler-22.03-x86_64.cfg
=> openEuler 24.03 LTS

mock-core-configs/etc/mock/fedora-41-aarch64.cfg, mock-core-configs/etc/mock/fedora-41-i386.cfg, mock-core-configs/etc/mock/fedora-41-ppc64le.cfg, mock-core-configs/etc/mock/fedora-41-s390x.cfg, mock-core-configs/etc/mock/fedora-41-x86_64.cfg, mock-core-configs/etc/mock/fedora-42-aarch64.cfg, mock-core-configs/etc/mock/fedora-42-i386.cfg, mock-core-configs/etc/mock/fedora-42-ppc64le.cfg, mock-core-configs/etc/mock/fedora-42-s390x.cfg, mock-core-configs/etc/mock/fedora-42-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl, mock-core-configs/etc/mock/templates/fedora-rawhide.tpl, mock-core-configs/mock-core-configs.spec, releng/release-notes-next/fedora-41-branching.feature
Branching F41 configs from Rawhide using `releng/rawhide-branching.sh`.
Schedule: https://fedorapeople.org/groups/schedule/f-41/f-41-all-tasks.html
=> configs: branch F41

.github/chronographer.yml
Refs:
* https://github.com/sanitizers/chronographer-github-app/issues/40#issuecomment-2323082256
* https://github.com/sanitizers/chronographer-github-app/commit/12a27ab
=> Configure Chronographer to skip labeling label-detected PRs

mock/mock.spec, releng/release-notes-next/fuse-overlayfs.bugfix
=> Add runtime dependency on fuse-overlayfs

docs/Plugin-PackageState.md
=> doc: slight update of the package_state plugin docs

.github/workflows/copr-builds.yml, .github/workflows/fedora-tox.yml
Complements: d2ff946215cff7a40b95aeba47033f946e0080c8
=> ci: fix the no-ci-builds label

behave/features/scrub-all-chroots.feature, behave/features/steps/other.py, behave/testlib.py, mock/docs/mock.1, mock/py/mock.py, mock/py/mockbuild/config.py, mock/py/mockbuild/scrub_all.py, mock/pylintrc, releng/release-notes-next/scrub-all-chroots.feature
=> Add a new option --scrub-all-chroots

mock/README.md
This is inherited from the Copr project.
=> README: copr build status in table

behave/features/hermetic-build.feature, mock-core-configs/etc/mock/templates/centos-stream-9.tpl, releng/release-notes-next/c9s-image-ready.config
=> configs: the stream9 image is "ready" for Mock bootstrap

mock/docs/mock.1
=> small typo

mock/py/mockbuild/config.py, releng/release-notes-next/restore-dnf_builddep_opts.bugfix
=> Restore dnf_builddep_opts

mock/mock.spec
Complements: f495a6cb7ac58c2de6611aea3b1ae059de73db01
=> mock: add source URL

mock/py/mockbuild/config.py, releng/release-notes-next/dnf-cmd.bugfix
=> Make --dnf-cmd compatible with DNF5

mock-core-configs/etc/mock/templates/opensuse-tumbleweed.tpl, releng/release-notes-next/fix-openSUSE-tumbleweed-update-failure-during-the-second-build.config
=> configs: fix openSUSE-tumbleweed update failure during the second build.

mock/py/mock-hermetic-repo.py
Can fix a few other cases of failures.
=> More robust retry mechanism for downloading rpms

docs/Mock-Core-Configs.md
=> add opensuse config maintainers

mock-core-configs/etc/mock/fedora-42-aarch64.cfg, mock-core-configs/etc/mock/fedora-42-i386.cfg, mock-core-configs/etc/mock/fedora-42-ppc64le.cfg, mock-core-configs/etc/mock/fedora-42-s390x.cfg, mock-core-configs/etc/mock/fedora-42-x86_64.cfg, mock-core-configs/etc/mock/fedora-43-aarch64.cfg, mock-core-configs/etc/mock/fedora-43-i386.cfg, mock-core-configs/etc/mock/fedora-43-ppc64le.cfg, mock-core-configs/etc/mock/fedora-43-s390x.cfg, mock-core-configs/etc/mock/fedora-43-x86_64.cfg, mock-core-configs/etc/mock/templates/fedora-eln.tpl, mock-core-configs/etc/mock/templates/fedora-rawhide.tpl, mock-core-configs/mock-core-configs.spec, releng/rawhide-branching.sh, releng/release-notes-next/fedora-42-branching.feature
Set:    rawhide == Fedora 43
Move:   41 => 42
Arches: aarch64 i386 ppc64le s390x x86_64
=> Move Rawhide to F43

testing-farm/tests/old-testsuite/test.sh
=> ci: do not swallow log output from test-suite

docs/Mock-Core-Configs.md
=> doc: update Mock-Core-Configs.md (maintainers)

mock-core-configs/etc/mock/templates/openeuler-20.03.tpl, mock-core-configs/etc/mock/templates/openeuler-22.03.tpl, mock-core-configs/etc/mock/templates/openeuler-24.03.tpl, releng/release-notes-next/openeuler-update.config
Fix:[#1539](https://github.com/rpm-software-management/mock/issues/1539)
=> bugfix: upgrade openeuler chroots to latest release and fix gpg check failed in 20.03 for issue#1539

docs/Mock-Core-Configs.md
=> doc: update the Anolis Mock configs maintainer

docs/Mock-Core-Configs.md
=> docs: mention two more Oracle Linux contacts

mock/integration-tests/runconfigs.sh
=> tests: do not try to build mock.src.rpm against navy-*

mock/py/mock.py, mock/py/mockbuild/buildroot.py, releng/release-notes-next/additional-package-installed-with-bootstrap.bugfix
=> bootstrap: automatically bind-mount local --additional-package

docs/Why-Mock.md, docs/index.md
=> Explain why Mock exists

mock-core-configs/etc/mock/alma+epel-10-aarch64.cfg, mock-core-configs/etc/mock/alma+epel-10-ppc64le.cfg, mock-core-configs/etc/mock/alma+epel-10-s390x.cfg, mock-core-configs/etc/mock/alma+epel-10-x86_64.cfg, mock-core-configs/etc/mock/alma+epel-10-x86_64_v2.cfg, mock-core-configs/etc/mock/alma-kitten+epel-10-x86_64_v2.cfg, mock-core-configs/etc/mock/almalinux-10-aarch64.cfg, mock-core-configs/etc/mock/almalinux-10-ppc64le.cfg, mock-core-configs/etc/mock/almalinux-10-s390x.cfg, mock-core-configs/etc/mock/almalinux-10-x86_64.cfg, mock-core-configs/etc/mock/almalinux-10-x86_64_v2.cfg, mock-core-configs/etc/mock/templates/almalinux-10.tpl, mock-core-configs/etc/mock/templates/almalinux-8.tpl, mock-core-configs/etc/mock/templates/almalinux-9.tpl, mock-core-configs/etc/mock/templates/almalinux-epel-10.tpl, mock-core-configs/etc/mock/templates/almalinux-epel-z-10.tpl, mock-core-configs/etc/mock/templates/almalinux-kitten-10.tpl, mock-core-configs/mock-core-configs.spec, releng/release-notes-next/almalinux10.config, releng/release-notes-next/almalinux_kitten_x86_64_v2.config
This is built on top of https://github.com/rpm-software-management/mock/pull/1586
=> Add AlmaLinux Kitten 10 x86_64_v2 configs, minor config cleanup
